### PR TITLE
Implement #2230 - Consume BindingAddress instead of ServerAddress

### PR DESCRIPTION
**Pull request by SonicGD**
Hello. I've tried to implement changes for #2230. I've done this:

1. Marked ServerAddress obsolete and suppress CS0618 errors in ServerAddressTests
2. Added reference to Microsoft.AspNetCore.Http in Kestrel.Core.csproj
3. Replaced usage of ServerAddress.FromUrl with BindingAddress.Parse
4. Update tests

I hope nothing is wrong =)

### CODE REVIEW

**Comment by Tratcher** [comment]
@halter73 @shirhatti let's decide if we can take this in release/2.2. If so then in 3.0 it'd be easy to remove the obsolete type.

**Comment by Tratcher** [comment]
@muratg @shirhatti thoughts on obsoleting [ServerAddress](https://github.com/aspnet/KestrelHttpServer/search?q=ServerAddress&unscoped_q=ServerAddress) in 2.2? It's officially a public type, but not one used in any public APIs.

**Comment by muratg** [comment]
@shirhatti thoughts on this?

**Comment by shirhatti** [comment]
If we take this in 2.2, we should probably update all servers. I'd like to see this https://github.com/aspnet/HttpSysServer/issues/422 go in as well

**Comment by Tratcher** [comment]
@shirhatti this is an implementation detail for the servers, not a public API we expect people to use directly with the servers.

**Comment by Tratcher** [comment]
Offline notes: This is fine to take in 2.2, and the HttpSys change would be orthogonal.

@SonicGD can you move this to the release/2.2 branch? If not then I can get to it next week.

**Comment by SonicGD** [comment]
@Tratcher Sure, will do today

**Comment by Tratcher** [comment]
Thanks

**Pull request merged**
