### PR TITLE
Reset frame streams on each request (#940).

### PR DESCRIPTION
**Pull request by cesarbs**
#940 

cc @halter73 @mikeharder @Tratcher

### CODE REVIEW

**Comment by benaadams** [comment]
Could this be added to a patch release? e.g. part of a 1.0.1 rather than a next version 1.1.0

**Comment by cesarbs** [comment]
@muratg @Eilon

**Comment by Eilon** [comment]
Given that this issue has a relatively simple workaround, it is very unlikely that we would release a patch for this.

If there are scenarios that are not addressed by the workaround, we could certainly reconsider.

**Comment by halter73** [comment]
:shipit:

**Pull request merged**
