### PR TITLE
Use type's namespace instead of assembly FullName

### LINKED ISSUE #775: Kestrel Logs print full assembly name as category name
Makes it harder to filter kestrel logs:

````
dbug: Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60[9]
      Connection id "0HKREDSFMRPFN" completed keep alive response.
```

This regressed here https://github.com/aspnet/KestrelHttpServer/commit/c48353f4ef1150b3197246de94a343ae8d9b29d4#diff-2a47c9b99ecab7d9ea77789228f7e771R44

### PR DESCRIPTION
**Pull request by khellang**
Same as #776, but targeting release. Fixes #775

### CODE REVIEW

**Comment by mikeharder** [comment]
@davidfowl: I can merge this to release and dev if you give it a :shipit: and get it approved for RC2.

**Comment by halter73** [comment]
:shipit:

**Comment by mikeharder** [comment]
@davidfowl: The previous value was the namespace `Microsoft.AspNetCore.Server.Kestrel` rather than the type `Microsoft.AspNetCore.Server.Kestrel.KestrelServer`.  Which do we want going forward?

**Comment by davidfowl** [comment]
The former one looks nicer

**Comment by khellang** [comment]
Actually, why not just use `typeof(KestrelServer).Name`? What is `CreateLogger <T>` using?

**Comment by halter73** [comment]
@khellang I agree that `Microsoft.AspNetCore.Server.Kestrel` looks nicer. It also makes the most sense to me, because the `KestrelServer` class isn't doing any logging directly.

**Comment by khellang** [comment]
Aight. Changed to namespace. Or did you just want med to hard code `Microsoft.AspNetCore.Server.Kestrel`?

Anything looks better than `Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60` :wink:

**Comment by davidfowl** [comment]
Yah, hardcode it

**Comment by khellang** [comment]
Hardcoded it is :grin:

**Comment by davidfowl** [comment]
@Eilon suggested we do `typeof(KestrelServer).Namespace`

**Comment by khellang** [comment]
Fffffffuuuuu. That's what I had before hard coding it :stuck_out_tongue_closed_eyes:

**Comment by Eilon** [comment]
Yeah don't listen to @davidfowl 😄

**Comment by benaadams** [comment]
Is `typeof(KestrelServer).Namespace` a compile time constant? (and if not why not...)

**Comment by Eilon** [comment]
@benaadams it's not, but I think in this case it's once per app.

**Comment by benaadams** [comment]
@Eilon raised issue https://github.com/dotnet/roslyn/issues/10972

**Comment by mikeharder** [comment]
We decided to take this change for post-RC2.  Manually merged to dev in 8a9840216c0793789e444f490009afe0a72acbb1.

**Pull request closed without merging**
