### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by davidfowl**

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Need to change `IndexOfVectorized` in https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/KestrelHttpParser.cs#L39 and https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/KestrelHttpParser.cs#L258 to `SequentialIndexOf`

**Comment by davidfowl** [comment]
Yes, I'm making the code changes now.

**Comment by benaadams** [comment]
I'd better sort out `IndexOf` then...

**Comment by davidfowl** [comment]
I just realized this completely nukes vectorization until we get the corefx changes...

**Comment by davidfowl** [comment]
Seems it's both slower and faster 😄 

## dev

```
                        Method |      Mean |    StdDev |      Op/s | Scaled | Scaled-StdDev | Allocated |
------------------------------ |---------- |---------- |---------- |------- |-------------- |---------- |
          PlaintextTechEmpower | 1.9557 us | 0.0493 us | 511322.33 |   1.00 |          0.00 |     349 B |
          PlaintextAbsoluteUri | 3.3417 us | 0.1155 us | 299249.88 |   1.71 |          0.07 |     692 B |
 PipelinedPlaintextTechEmpower | 1.6518 us | 0.0595 us | 605401.52 |   0.85 |          0.04 |     348 B |
                    LiveAspNet | 3.7546 us | 0.0852 us | 266339.63 |   1.92 |          0.06 |   1.07 kB |
           PipelinedLiveAspNet | 3.5700 us | 0.1009 us | 280114.53 |   1.83 |          0.07 |   1.07 kB |
                       Unicode | 5.9010 us | 0.1351 us | 169463.41 |   3.02 |          0.10 |   1.85 kB |
              UnicodePipelined | 5.8640 us | 0.0909 us | 170533.27 |   3.00 |          0.09 |   1.86 kB |
```

## PR
```
                        Method |      Mean |    StdDev |      Op/s | Scaled | Scaled-StdDev | Allocated |
------------------------------ |---------- |---------- |---------- |------- |-------------- |---------- |
          PlaintextTechEmpower | 1.8755 us | 0.0455 us | 533189.99 |   1.00 |          0.00 |     349 B |
          PlaintextAbsoluteUri | 3.1970 us | 0.0544 us | 312790.57 |   1.71 |          0.05 |     692 B |
 PipelinedPlaintextTechEmpower | 1.5729 us | 0.0445 us | 635775.44 |   0.84 |          0.03 |     348 B |
                    LiveAspNet | 3.6640 us | 0.1282 us | 272924.41 |   1.95 |          0.08 |   1.07 kB |
           PipelinedLiveAspNet | 3.4709 us | 0.1040 us | 288109.83 |   1.85 |          0.07 |   1.07 kB |
                       Unicode | 5.6961 us | 0.1247 us | 175560.04 |   3.04 |          0.10 |   1.85 kB |
              UnicodePipelined | 5.8893 us | 0.1323 us | 169799.83 |   3.14 |          0.10 |   1.86 kB |
```

**Pull request merged**
