### PR TITLE
Implement APM methods in streams (#1335)

### PR DESCRIPTION
**Pull request by cesarbs**
#1335 

Basically just replicated the changes from https://github.com/aspnet/KestrelHttpServer/commit/4337d2a4a751ee7ccb0e0c460670c0abd044d040 and https://github.com/aspnet/KestrelHttpServer/commit/5aee5247685b3e3f9157e229dfc2c7ba9248dcb3.

@halter73 @mikeharder @Eilon

### CODE REVIEW

**Comment by davidfowl** [comment]
Where's the CI run?

**Comment by davidfowl** [comment]
Here's a much more efficient helper to go from Task to APM:

https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines/TaskToApm.cs

**Comment by halter73** [comment]
@davidfowl  Cool. Using a custom IAsyncResult or the original Task if it has the correct AsyncState seems a lot more efficient than always using ContinueWith() and a TCS. Special casing completed tasks to avoid closure allocations is also smart.

Unfortunately, this change is a 1.0.3 backport, so we should probably use the well tested code that still immensely improves the perf of the HttpsConnectionFilter on desktop .NET.

We should look into using TaskToApm for 2.0. Is TaskToApm available publicly in any packages we produce? If not, are there any plans to do so?

**Comment by cesarbs** [comment]
Was about to reply that although that's more efficient, we should stick to the well tested code we have in 1.1 for this backport.

**Comment by Drawaes** [comment]
I would be interested if it is public. Internal classes are making copy/paste boring

**Comment by davidfowl** [comment]
> Unfortunately, this change is a 1.0.3 backport, so we should probably use the well tested code that still immensely improves the perf of the HttpsConnectionFilter on desktop .NET.

This code is well tested, it came from corefx and is used there. We're already using it indirectly (via SSL Stream).

> We should look into using TaskToApm for 2.0. Is TaskToApm available publicly in any packages we produce? If not, are there any plans to do so?

Maybe we can add something in System.Threading.Task.Extensions?
/cc @stephentoub

**Comment by halter73** [comment]
Fair enough. The integration is well tested as well. TaskToApm seems simple enough to use correctly, but I don't think the perf of this backport is huge concern as long as it isn't so bad that it's completely broken like before due to the synchronous calls that were made.

We should also update all of our Stream implementations at once.

**Pull request merged**
