### PR TITLE
Add option to remove the Server header

### LINKED ISSUE #852: How to remove Response header server:krestel
From https://github.com/aspnet/Mvc/issues/4689

As a security concern how can we remove "Server:krestel" from Response Header?

### PR DESCRIPTION
**Pull request by khellang**
Closes #852. Take it or leave it :wink:

### CODE REVIEW

**Comment by Tratcher** [comment]
:shipit:

**Comment by halter73** [comment]
Thannks @khellang! Since you already started on this with ef35d23, do you plan on submitting a PR for #223 too?

**Comment by sadjadbp** [comment]
Thanks seem like the result would be in RC3 like this (in Program.cs)

`.UseKestrel((options) => { options.AddServerHeader = false; })`

**Comment by khellang** [comment]
> Since you already started on this with ef35d23, do you plan on submitting a PR for #223 too?

@halter73 Yep. Submitted #862 :grin:

**Comment by GuardRex** [comment]
@khellang @halter73 This was merged, but I'm not getting access to it. `aspnetvnext` feed, correct?

**Comment by cesarbs** [comment]
@GuardRex We haven't pushed a build with this yet. You can try using the `aspnetcidev` feed.

**Pull request merged**
