### PR TITLE
[Platform] sync fast path

### PR DESCRIPTION
**Pull request by benaadams**
Is https://github.com/aspnet/KestrelHttpServer/pull/2575

> Rather than `Reader.AdvanceTo` for every request in the input; only Advance the Reader once all the input has been processed (e.g. 1 once per loop rather than 16 times per loop for pipelined)
>
> Rather than `Reader.ReadAsync` for every request in the input; only Read for more data once all the input has been processed (e.g. 1 once per loop rather than 16 times per loop for pipelined) 

Then adds a sync fast-path for the tight parsing/response loop

/cc @davidfowl @sebastienros

### CODE REVIEW

**Comment by benaadams** [comment]
Hopefully now should have > +3%

**Comment by benaadams** [comment]
ProcessRequests (568k calls) is fast-path entry point which then calls into ProcessRequestAsync (9M calls)

image

**Comment by benaadams** [comment]
Also added tweaks for 2.2 libs which I saw along the way

ReadOnlySpan.CopyTo https://github.com/dotnet/coreclr/issues/18005 -> https://github.com/dotnet/coreclr/pull/18006

Split BufferReader.Advance with fast path https://github.com/aspnet/Common/pull/357
Buffer Reader.Advance move all exceptional cases to slow path https://github.com/aspnet/Common/pull/358
BufferReader .ctor inline fast-path in MoveNext https://github.com/aspnet/Common/pull/359

**Comment by davidfowl** [comment]
Took this instead https://github.com/aspnet/KestrelHttpServer/pull/2575

**Pull request closed without merging**
