### PR TITLE
Fix more test failures caused by connection resets

### PR DESCRIPTION
**Pull request by halter73**
#1167

### CODE REVIEW

**Comment by cesarbs** [comment]
Failed https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.3705

The fix is to change `Send` to `SendEnd`. What happens is that if we happen to close the connection before all data has been read, the connection will be reset and `TestConnection` will fail to read the response.

If you send a FIN then the RST is not sent when the socket is shutdown.

Here's a gist with some code to play with: https://gist.github.com/cesarbs/2f166d2ff21ee138d1ea8022a85e295b

Watch the network while running it and you'll see what I'm talking about:

* The way it is now, you'll only see FINs sent from the server on shutdown
* If you remove the `Shutdown` in the client thread, you'll see the server FIN followed by an RST
* If you change the `Receive` in the server thread to receive 2 bytes, you won't see RSTs

**Comment by cesarbs** [comment]
I was playing with this and `SendEnd` isn't the right fix either. Switching to `SendAll` seems to do the trick i.e. avoid RSTs from the server so the response can be read. The problem with `Send`/`SendEnd` is that they send one character at a time - if it's still sending when the server sends the error response and closes the connection, `Receive` fails when trying to read the response.

Your change also doesn't work because the server just spins waiting for another char so it can begin parsing the chunked prefix (see `MessageBody.ForChunkedEncoding.ParseChunkedPrefix()`).

**Comment by cesarbs** [comment]
One interesting addition to this test is to add a `bool` that's set to `true` in the `catch` block in the app. That way we can be sure we actually caught the `BadHttpRequestException`. Then `Assert.True()` it.

**Comment by halter73** [comment]
I was able to fix this by simply adding one more "g" character. Our current implementation always attempts to read at least 2 bytes before starting to parse the chunk prefix. This could regress if the implementation changes, but no worse than it is today.

**Comment by cesarbs** [comment]
Ok, I supposed that works too. Are you adding the `bool` I suggested?

**Pull request merged**
