### PR TITLE
Micro optimizations

### PR DESCRIPTION
**Pull request by niemyjski**
I was playing around with Kestrel a little bit and decided to take a look at the code. I couldn't build in VS 2015 (Not using Update 1 RC), but could build via the command line. Please give me feedback on anything I could change or update. It's a learning experience playing with libuv :)

* Enums use byte instead of int. This will need to be benchmarked, ints may preform better on some cpus.
* Fixed an issue where a new buffer was being created when it didn't need to be.
* Don't write to streams or do extra work (allocations) if we don't need to be.

### CODE REVIEW

**Comment by niemyjski** [comment]
I see that there are other cases where were allocating ArraySegments. I'd need to dive into this more to see if we could save from allocating one or more of them. I do see cases where we might be able to save some additional time by checking to see if the buffer contains any data before calling write.

**Comment by halter73** [comment]
Thanks for the PR.

Generally speaking, we don't like to take perf changes that don't come with measurements showing either a request-per-second improvement or significant per-request heap allocation reduction.

I haven't measured the perf impact of the myself, but from looking at the changes I don't suspect this does either. Feel free to reopen if you have measurements that prove me wrong.

**Comment by niemyjski** [comment]
What do you recommend me doing to add tests for measurements? It's kinda hard to say this increases by x on my machine cause it can be different per machine..

**Comment by khellang** [comment]
@niemyjski You can establish a baseline on your machine, then apply the changes and measure the difference?

**Comment by niemyjski** [comment]
Do you have a test that outputs benchmarks I can then paste a before and after?

Sent from Outlook




On Tue, Dec 1, 2015 at 1:33 PM -0800, "Kristian Hellang" <notifications@github.com> wrote:












@niemyjski You can establish a baseline on your machine, then apply the changes and measure the difference?

**Comment by khellang** [comment]
Since these are "micro optimizations", I don't know how much measurable difference there will be running https://github.com/aspnet/benchmarks, but you could just use a simple stopwatch and do the same thing over and over for x iterations?

**Comment by halter73** [comment]
https://github.com/aspnet/benchmarks also shows how to use `wrk` to get measurements. If you have a linux machine/vm to run wrk on, that's probably a bit easier than setting up your own load test harness. Unfortunately, I also don't expect the changes I've seen made so far in this PR will make a measurable impact.

**Comment by niemyjski** [comment]
I ran these across different vms... Doing 32 threads on OS X caused some errors to be thrown by `wrk`.

before 
```
Running 10s test @ http://10.211.55.6:5001/plaintext
  26 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    15.12ms   11.84ms 115.67ms   79.08%
    Req/Sec     6.47k     1.66k   21.03k    78.77%
  1676891 requests in 10.07s, 211.10MB read
  Socket errors: connect 7, read 0, write 0, timeout 0
Requests/sec: 166514.06
Transfer/sec:     20.96MB
```
after
```
Please write a guide on how to use your own kestrel source... You can't expect people to test this if you make users jump through 10 hoops just to do a pull request. I tried updating references/adding it as an existing project reference, updating global.json/project.json without any luck after a half hour. I could get it to compile but runtime / assembly load errors all over the place...
```

**Comment by halter73** [comment]
Sorry for the frustration this has caused you.

First of all, it might be better to lower the connection count if you are seeing connect errors since those can mess with the results. As long as you use the same parameters for each run, you should be fine.

[Updating the global.json](https://github.com/aspnet/Home/wiki/Engineering-guidelines#local-debugging-of-cross-repo-dependencies) is the way I normally go about testing changes across repositories. I'm not sure why you ran into assembly load errors. Have you tried rerunning `dnu restore` in the root of both repos?

If that works for you, I'll be sure to add the `dnu restore` step to the engineering guidelines I linked to. If that doesn't work for you, feel free to add more details about the errors and we can try to figure it out.

The reason I closed this is because I don't expect you will see any measurable improvements from this PR, but I'm glad to try to help anyone who wants to get started contributing to Kestrel.

**Comment by niemyjski** [comment]
Is there any chance you can try running my changes as well really quick? I have other things running on my macbook (elastic search restores and other things that could be skewing the results)

To get it to work I had to do this
remove code from `spcm` file:

   public class StandardsPoliceCompileModule : Microsoft.StandardsPolice.StandardsPoliceCompileModule
    {
    }

Add `"../KestrelHttpServer/src"` to global.json and add the existing kestrel project to the solution

**Comment by halter73** [comment]
Doh! I know the problem you are running into, and this one is specific Kestrel.

You need to add `../KestrelHttpServer/tools` to your global.json too (though removing StandardsPoliceCompileModule also works). Maybe this should be added to the Kestrel README.

Though we usually like the submitter of perf changes to provide their own measurements first, I'll try testing the PR in our perf lab in the next batch of tests since it's been such a hassle for you.

**Comment by niemyjski** [comment]
Were you able to run these tests?

**Comment by AspNetSmurfLab** [comment]
__Baseline (origin/dev dff3a4f):__

	Running 15s test @ http://10.0.0.100:5001/plaintext
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency    11.57ms   28.80ms 363.98ms   90.57%
	    Req/Sec    25.10k     3.54k   76.12k    94.73%
	  11993716 requests in 15.10s, 1.47GB read
	Requests/sec: 794311.34
	Transfer/sec:     99.99MB

	Running 15s test @ http://10.0.0.100:5001/plaintext
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency    13.26ms   36.69ms 495.50ms   91.72%
	    Req/Sec    25.10k     3.23k   63.14k    90.65%
	  11973370 requests in 15.10s, 1.47GB read
	Requests/sec: 793022.60
	Transfer/sec:     99.83MB


	Running 15s test @ http://10.0.0.100:5001/plaintext
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency     9.54ms   25.18ms 366.01ms   90.77%
	    Req/Sec    25.12k     2.92k   63.19k    91.38%
	  12014880 requests in 15.10s, 1.48GB read
	Requests/sec: 795755.29
	Transfer/sec:    100.17MB


__Merged (niemyjsk/dev):__

	Running 15s test @ http://10.0.0.100:5001/plaintext
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency    14.21ms   33.14ms 379.55ms   87.93%
	    Req/Sec    24.92k     2.49k   48.33k    79.73%
	  11947374 requests in 15.10s, 1.47GB read
	Requests/sec: 791252.40
	Transfer/sec:     99.61MB


	Running 15s test @ http://10.0.0.100:5001/plaintext
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency    13.27ms   38.14ms 602.15ms   89.61%
	    Req/Sec    25.07k     2.18k   41.86k    76.15%
	  12033096 requests in 15.10s, 1.48GB read
	Requests/sec: 796933.36
	Transfer/sec:    100.32MB


	Running 15s test @ http://10.0.0.100:5001/plaintext
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency    13.24ms   32.73ms 412.07ms   91.41%
	    Req/Sec    25.00k     2.32k   40.14k    77.99%
	  11993584 requests in 15.10s, 1.47GB read
	Requests/sec: 794309.38
	Transfer/sec:     99.99MB

**Comment by niemyjski** [comment]
So it looks like it may be faster two of the requests were

Sent from Outlook Mobile




On Tue, Dec 8, 2015 at 4:37 PM -0800, "ASP.NET Smurf Lab" <notifications@github.com> wrote:












Baseline (origin/dev dff3a4f):

Running 15s test @ http://10.0.0.100:5001/plaintext
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.57ms   28.80ms 363.98ms   90.57%
    Req/Sec    25.10k     3.54k   76.12k    94.73%
  11993716 requests in 15.10s, 1.47GB read
Requests/sec: 794311.34
Transfer/sec:     99.99MB

Running 15s test @ http://10.0.0.100:5001/plaintext
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.26ms   36.69ms 495.50ms   91.72%
    Req/Sec    25.10k     3.23k   63.14k    90.65%
  11973370 requests in 15.10s, 1.47GB read
Requests/sec: 793022.60
Transfer/sec:     99.83MB


Running 15s test @ http://10.0.0.100:5001/plaintext
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     9.54ms   25.18ms 366.01ms   90.77%
    Req/Sec    25.12k     2.92k   63.19k    91.38%
  12014880 requests in 15.10s, 1.48GB read
Requests/sec: 795755.29
Transfer/sec:    100.17MB




Merged (niemyjsk/dev):

Running 15s test @ http://10.0.0.100:5001/plaintext
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    14.21ms   33.14ms 379.55ms   87.93%
    Req/Sec    24.92k     2.49k   48.33k    79.73%
  11947374 requests in 15.10s, 1.47GB read
Requests/sec: 791252.40
Transfer/sec:     99.61MB


Running 15s test @ http://10.0.0.100:5001/plaintext
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.27ms   38.14ms 602.15ms   89.61%
    Req/Sec    25.07k     2.18k   41.86k    76.15%
  12033096 requests in 15.10s, 1.48GB read
Requests/sec: 796933.36
Transfer/sec:    100.32MB


Running 15s test @ http://10.0.0.100:5001/plaintext
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.24ms   32.73ms 412.07ms   91.41%
    Req/Sec    25.00k     2.32k   40.14k    77.99%
  11993584 requests in 15.10s, 1.47GB read
Requests/sec: 794309.38
Transfer/sec:     99.99MB

**Comment by niemyjski** [comment]
@halter73 it looks like there was some improvement..

**Comment by halter73** [comment]
There was no RPS improvement.

Average baseline RPS: (794311.34+793022.60+795755.29)/3 = 794363
Average merged RPS: (791252.40+796933.36+794309.38)/3 = 794165

I reran with some of the new perf changes we're working on, and again I see no improvement:

Baseline:

    Running 15s test @ http://10.0.0.100:5001/plaintext
      32 threads and 256 connections
      Thread Stats Avg      Stdev Max   +/- Stdev
    Latency     3.66ms    8.98ms 256.80ms   95.96%
        Req/Sec    32.18k     1.84k   53.22k    83.92%
      15438089 requests in 15.10s, 1.90GB read
    Requests/sec: 1022388.78
    Transfer/sec:    128.70MB

    Running 15s test @ http://10.0.0.100:5001/plaintext
      32 threads and 256 connections
      Thread Stats Avg      Stdev Max   +/- Stdev
    Latency     6.66ms   20.73ms 253.68ms   94.88%
        Req/Sec    32.44k     2.71k   75.68k    89.34%
      15544663 requests in 15.10s, 1.91GB read
    Requests/sec: 1029433.91
    Transfer/sec:    129.59MB

    Running 15s test @ http://10.0.0.100:5001/plaintext
      32 threads and 256 connections
      Thread Stats Avg      Stdev Max   +/- Stdev
    Latency     3.62ms    8.77ms 182.98ms   96.77%
        Req/Sec    32.20k     1.99k   63.61k    87.09%
      15442533 requests in 15.10s, 1.90GB read
    Requests/sec: 1022693.72
    Transfer/sec:    128.74MB

Merged:

    Running 15s test @ http://10.0.0.100:5001/plaintext
      32 threads and 256 connections
      Thread Stats Avg      Stdev Max   +/- Stdev
    Latency     4.39ms   12.16ms 407.56ms   94.32%
        Req/Sec    32.02k     2.07k   51.25k    80.33%
      15363635 requests in 15.10s, 1.89GB read
      Socket errors: connect 0, read 0, write 90, timeout 0
    Requests/sec: 1017461.70
    Transfer/sec:    128.08MB

    Running 15s test @ http://10.0.0.100:5001/plaintext
      32 threads and 256 connections
      Thread Stats Avg      Stdev Max   +/- Stdev
    Latency     4.50ms   14.03ms 273.96ms   94.10%
        Req/Sec    31.99k     1.96k   57.35k    85.37%
      15340593 requests in 15.10s, 1.89GB read
    Requests/sec: 1016009.48
    Transfer/sec:    127.90MB

    Running 15s test @ http://10.0.0.100:5001/plaintext
      32 threads and 256 connections
      Thread Stats Avg      Stdev Max   +/- Stdev
    Latency     4.81ms   12.76ms 382.76ms   94.63%
        Req/Sec    31.78k     2.22k   66.71k    86.71%
      15232784 requests in 15.10s, 1.87GB read
    Requests/sec: 1008773.67
    Transfer/sec:    126.99MB

Again the numbers look a little better without these changes merged. Frankly, the numbers are so close that I could chalk the differences up to variance in the test. But there is certainly not enough there to merge this change.

**Pull request closed without merging**
