### PR TITLE
[LTS] Updating to version 1.0.2.

### PR DESCRIPTION
**Pull request by cesarbs**
Not really merging this to `master` - just want some 👀 on it before creating the `rel/1.0.2` branch.

cc @pranavkm @halter73 @muratg @Eilon 

@muratg I haven't bumped the hosting dependency to 1.0.1 yet because there's no such package. How are we going to stage this?

### CODE REVIEW

**Comment by muratg** [comment]
@cesarbs hosting should build first and produce the package. cc @JunTaoLuo @Tratcher

**Comment by pranavkm** [comment]
LKGTM

**Comment by JunTaoLuo** [comment]
I'm still waiting on getting a 1.0.3 patch build to succeed before I build the hosting package, so let's wait for that first.

**Comment by halter73** [comment]
Weird restore error on os x travis:

    Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
     (Exception from HRESULT: 0x8007007E)
       at Interop.CryptoInitializer.EnsureOpenSslInitialized()
       at Interop.CryptoInitializer..cctor()
       --- End of inner exception stack trace ---
       at Interop.Crypto..cctor()
       --- End of inner exception stack trace ---
       at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
       at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
       at System.IO.Path.GetRandomFileName()
       at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
       at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
       at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
       at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
       at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
       at Microsoft.DotNet.Cli.Program.Main(String[] args)
    .build/KoreBuild.sh: line 82:  4558 Abort trap: 6           dotnet restore "$toolsProject" --packages $scriptRoot -v Minimal

https://travis-ci.org/aspnet/KestrelHttpServer/jobs/172731253

I'm assuming that's unrelated to this change though. :ship:

**Comment by JunTaoLuo** [comment]
@halter73 that's because .travis.yml is out of date.

**Comment by cesarbs** [comment]
About the branch name: should I name it after the package version (1.0.2) or release version (1.0.3 - right?)?

**Comment by cesarbs** [comment]
Updated travis per https://github.com/aspnet/KestrelHttpServer/blob/7704ddfc7f3aaff00e9754ed32e2398d300fd842/.travis.yml (thanks @JunTaoLuo).

**Comment by pranavkm** [comment]
@Eilon - 

> About the branch name: should I name it after the package version (1.0.2) or release version (1.0.3 - right?)?

Mvc used rel/1.0.2. Should we try and sync up the release names instead?

**Comment by Eilon** [comment]
@pranavkm I'd prefer that within a repo that the branch name match the version...

**Comment by cesarbs** [comment]
I woke up this morning thinking creating this branch might not be necessary - we're not really patching Kestrel, just adding some regression tests (per #1171). Can't I just check those in directly to `master`?

**Comment by cesarbs** [comment]
https://github.com/aspnet/KestrelHttpServer/commit/7bf6f0d2ab18b176e40aa42d84b75d7af58721a0

**Pull request closed without merging**
