### PR TITLE
Added test for query string without path

### PR DESCRIPTION
**Pull request by davidfowl**
/cc @halter73 @cesarbs

### CODE REVIEW

**Comment by davidfowl** [comment]
@cesarbs Turns out this explodes on the current kestrel 😄

**Comment by natemcmaster** [comment]
This is one of the issues I'll address in https://github.com/aspnet/KestrelHttpServer/issues/1279

**Comment by halter73** [comment]
@davidfowl Do you want someone to update the davidfowl/added-bad-target-test branch so this test passes and then merge?

**Comment by davidfowl** [comment]
@halter73 I think it depends on how complicate the fix it. Goal was to reduce number of changes to this branch unless necessary. I found this while writing the state machine for dev. @natemcmaster claims that it'll be fixed with other scheduled work so I'm not sure if there's a short term thing we should do here.

**Comment by davidfowl** [comment]
Closing for now

**Pull request closed without merging**
