### PR TITLE
AddressRegistrationTests should get local IPs from System.Net.NetworkInformation (#796)

### PR DESCRIPTION
**Pull request by mikeharder**
@cesarbs, @halter73 

#796

### CODE REVIEW

**Comment by halter73** [comment]
Seems to be causing an Travis OS X failure :cry:

https://travis-ci.org/aspnet/KestrelHttpServer/jobs/129316019

    fail:     Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_IPv6_Success(addressInput: "http://[fe80::1]:0/", testUrls: Func`2 { Method = System.String[] GetTestUrls(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = null }) [FAIL]
    info:       System.AggregateException : One or more errors occurred. (Error -49 EADDRNOTAVAIL address not available)
    info:       ---- Microsoft.AspNetCore.Server.Kestrel.Networking.UvException : Error -49 EADDRNOTAVAIL address not available
    info:       Stack Trace:
    info:            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    info:            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    info:            at System.Threading.Tasks.Task.Wait()
    info:            at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.CreateServer(ServerAddress address)
    info:            at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
    info:            at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
    info:            at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__4.MoveNext()
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    info:            at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_IPv6_Success>d__2.MoveNext()
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:         ----- Inner Stack Trace -----
    info:            at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
    info:            at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
    info:            at Microsoft.AspNetCore.Server.Kestrel.Networking.UvTcpHandle.Bind(ServerAddress address)
    info:            at Microsoft.AspNetCore.Server.Kestrel.Http.TcpListener.CreateListenSocket()
    info:            at Microsoft.AspNetCore.Server.Kestrel.Http.Listener.<>c.<StartAsync>b__6_0(Object state)
    fail:     Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_IPv6_Success(addressInput: "http://[fe80::250:56ff:fea6:feb]:0/", testUrls: Func`2 { Method = System.String[] GetTestUrls(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = null }) [FAIL]
    info:       System.AggregateException : One or more errors occurred. (Error -49 EADDRNOTAVAIL address not available)
    info:       ---- Microsoft.AspNetCore.Server.Kestrel.Networking.UvException : Error -49 EADDRNOTAVAIL address not available
    info:       Stack Trace:
    info:            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    info:            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    info:            at System.Threading.Tasks.Task.Wait()
    info:            at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.CreateServer(ServerAddress address)
    info:            at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
    info:            at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
    info:            at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__4.MoveNext()
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    info:            at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_IPv6_Success>d__2.MoveNext()
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:         --- End of stack trace from previous location where exception was thrown ---
    info:            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    info:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    info:         ----- Inner Stack Trace -----
    info:            at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
    info:            at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
    info:            at Microsoft.AspNetCore.Server.Kestrel.Networking.UvTcpHandle.Bind(ServerAddress address)
    info:            at Microsoft.AspNetCore.Server.Kestrel.Http.TcpListener.CreateListenSocket()
    info:            at Microsoft.AspNetCore.Server.Kestrel.Http.Listener.<>c.<StartAsync>b__6_0(Object state)

**Comment by mikeharder** [comment]
Looks like Travis OS X is unable to bind to link-local IPv6.  I'll investigate further and probably end up adding another skip condition.

**Comment by halter73** [comment]
@mikeharder Do you still want to investigate the travis os x issue or just add a skip condition?

**Comment by mikeharder** [comment]
Travis OSX failure was caused by https://github.com/dotnet/corefx/issues/8458.  Once we pickup binaries with this fix, my change should work as-is.

**Comment by mikeharder** [comment]
@halter73, @cesarbs: Rebased and both Travis and AppVeyor are passing.

**Comment by halter73** [comment]
:shipit:

**Pull request merged**
