### PR TITLE
Merge Kestrel into Microsoft.AspNet.Server.Kestrel

### PR DESCRIPTION
**Pull request by halter73**
#11

### CODE REVIEW

**Comment by davidfowl** [comment]
Hella breaking change here. Alert the presses on https://github.com/aspnet/Announcements

**Comment by halter73** [comment]
@davidfowl I definitely planned on doing that. I was waiting for the sign off first. I'm not sure I want push this change today since our CI server is down.

**Comment by Eilon** [comment]
:shipit: but also need to update all the other repos that use Kestrel.

**Comment by halter73** [comment]
Fixed by d97b02696f05f5c367720d46768829132f5e65e2 and 097fb35ddf7f9ff310938586a5490cb5988dcf5f

**Pull request closed without merging**
