### PR TITLE
Don't treat canceled reads as end of input

### PR DESCRIPTION
**Pull request by halter73**
@pakrym @cesarbs

### CODE REVIEW

**Comment by halter73** [comment]
This fixes the failing RequestsCanBeAbortedMidRead in dev.

**Comment by cesarbs** [comment]
Is the test that broke in the CI a proper test for this, or does this warrant a new test?

**Comment by cesarbs** [comment]
How hard is it to mock `_input` and write a small unit test to verify this behavior?

**Comment by pakrym** [comment]
Looks good, but having tests would be nice.

**Comment by davidfowl** [comment]
Why is appveyor failing?

**Comment by pakrym** [comment]
@davidfowl I think it's race that was fixed by pipelines PR.

**Comment by halter73** [comment]
The test that this fixes is about as good as a functional test is going to get. I will look into adding unit tests for the two affected classes though.

**Pull request merged**
