### PR TITLE
Target dnx451

### PR DESCRIPTION
**Pull request by bricelam**
Reverts fb8cf86f715ff8f865ba077117558b22fdeffe50 on DNX

### CODE REVIEW

**Comment by cesarbs** [comment]
@bricelam Can you give more context on why this is needed? I thought we weren't going to target `dnx451` anymore.

**Comment by bricelam** [comment]
It's so people can continue using RC1 tools with our packages.

**Comment by khellang** [comment]
> It's so people can continue using RC1 tools with our packages.

Shouldn't `net451` cover this?

**Comment by davidfowl** [comment]
@bricelam I think we should just let people put this in their projects instead.

**Comment by bricelam** [comment]
The commit referenced broke that. CLI pulls in *some* facades, but DNX doesn't get any.

@davidfowl I'm fine with that. @dougbu requested this change.

**Comment by dougbu** [comment]
>  @dougbu requested this change

Yes but @Eilon was less concerned about me than the many people out in the real world trying to use `dev`.

**Comment by muratg** [comment]
Where are we with these? Still needed?

**Comment by davidfowl** [comment]
We shouldn;t make these temporary changes to add dnx anywhere. We're close to having what we want to ship ideally. I'd rather hack DNX to make it work than change the shipping packages.

**Comment by Eilon** [comment]
@davidfowl I'm actually ok either way - the question is how desperate the need is. If adding it to Kestrel unblocks something we need right now, let's do that. But if it's not a pressing need and we can wait for a DNX hack, that's certainly a better option.

**Comment by bricelam** [comment]
Recalling. After chatting with @Eilon, we decided that adding the facades to user's `project.json` is an acceptable workaround.

**Pull request closed without merging**
