### PR TITLE
Add diagnostic messages to show hanging tests in the output

### PR DESCRIPTION
**Pull request by davidfowl**
Now test hangs will show up.

### CODE REVIEW

**Comment by halter73** [comment]
Now that we store artifacts are pretty much all our build servers, the technique I use to find the hanging test is to run `grep -rL "Finished test"` in the log directory. Only logs for incomplete tests will show up. Unfortunately this doesn't help for unit tests without logging enabled, but hopefully unit tests aren't the ones that are hanging. So maybe that an option if diagnosticMessages are a no-go.

**Comment by davidfowl** [comment]
It's fine, SignalR has it turned on, it's not that bad.

**Comment by mikeharder** [comment]
I was the last person to try enabling this, and I reverted it for the [following reasons](https://github.com/aspnet/KestrelHttpServer/pull/2522):

> - xUnit diagnostic messages were enabled in #2505 to help identify hung tests
> - However, this also enables log messages for non-serializable theory data (https://github.com/aspnet/KestrelHttpServer/issues/2509), which adds noise to logs
> - It doesn't seem possible to disable the "non-serializable data" messages but keep the "long-running test" messages
> - Converting all tests to serializable theory data is expensive and complicates test code
> - The best solution for now is to revert xUnit diagnostic messages to disabled, and re-enable when needed to identify hung tests

**Comment by davidfowl** [comment]
The log isn't that much noiser though https://ci3.dot.net/job/aspnet_KestrelHttpServer/job/release_2.2/job/osx-Configuration_Release_prtest/178/consoleFull.

**Comment by mikeharder** [comment]
The log now has 46 warnings like the following.  Note these add noise to local developer builds as well as CI builds.  We previously decided the noise of these warnings was not worth the benefit of identifying hung tests, and we didn't want to spend the time fixing the non-serializable parameters.

```
[xUnit.net 00:00:00.32] InMemory.FunctionalTests: Non-serializable data ('System.Object[]') found for
'Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2ConnectionTests.HEADERS_Received_HeaderBlockContainsDuplicatePseudoHeaderField_StreamError';
falling back to single test case.
```

**Comment by halter73** [comment]
@davidfowl Are you going to close this then?

**Comment by davidfowl** [comment]
No I think this needs to be on.

**Pull request closed without merging**
