### PR TITLE
Remove the custom C# compiler now that we're using the 2.2 SDK

### PR DESCRIPTION
**Pull request by davidfowl**
- It should speed builds up considerably

/cc @VSadov We're going to be getting compilers from the SDK from now on. So we should make sure the changes propagate there regularly.

### CODE REVIEW

**Comment by pakrym** [comment]
This has to be done in `SignalR` and `Benchmarks` too

**Comment by natemcmaster** [comment]
Do we need to set `LangVersion` to 7.2 at some point?

**Comment by davidfowl** [comment]
> Do we need to set LangVersion to 7.2 at some point?

If we don't plan to always use latest.

**Comment by halter73** [comment]
I was going to close #1778, but the issue was already closed back in June. Good thing we remembered 😅

**Pull request merged**
