### PR TITLE
[WIP][2.2] Remove lock contention in IOQueue

### PR DESCRIPTION
**Pull request by benaadams**
For testing https://github.com/aspnet/KestrelHttpServer/pull/3093

@sebastienros version for benchmarking; should effect pipelined, may effect non-pipelined

### CODE REVIEW

**Comment by benaadams** [comment]
Seems to stick net45x in an infinite loop; am I missing something? /cc @halter73

**Comment by davidfowl** [comment]
This should be against 3.0 (master)

**Comment by benaadams** [comment]
> This should be against 3.0 (master)

Yeah, that's this one https://github.com/aspnet/KestrelHttpServer/pull/3093

This is only to benchmark more easily on 2.2; which is why I've flagged it as [WIP]

**Comment by sebastienros** [comment]
I am not seeing any improvements on either pipelined or non-pipelined, windows or linux. Should it be an obvious win and my tests are wrong?

**Comment by benaadams** [comment]
K, thanks for trying. I was seeing the contention against .NET Core 3.0 (built from current source); so it may be since that is faster, contention comes more into play. Will keep the other PR open.

**Pull request closed without merging**
