### PR TITLE
Move Int64 parsing logic to HttpAbstractions

### PR DESCRIPTION
**Pull request by JunTaoLuo**
#1227 

requires https://github.com/aspnet/HttpAbstractions/pull/738

cc @Tratcher @cesarbs @halter73

### CODE REVIEW

**Comment by halter73** [comment]
LGTM pending the HttpAbstractions changes.

**Comment by cesarbs** [comment]
Build is upset.

**Comment by JunTaoLuo** [comment]
@cesarbs because it needs the changes in HttpAbstractions.

**Comment by cesarbs** [comment]
@JunTaoLuo Oh I should have checked. For whatever reason I thought that was checked in already.

**Pull request merged**
