### PR TITLE
Fix ThreadCountTests so they pass on OSX.

### PR DESCRIPTION
**Pull request by cesarbs**
@halter73 @mikeharder @BrennanConroy

### CODE REVIEW

**Comment by pakrym** [comment]
Does this mean that `HttpClient` leaks handles?

**Comment by cesarbs** [comment]
@pakrym not sure.

@stephentoub any insight on what could be happening here? Before the change we were getting curl exceptions saying it got an empty response from the server.

**Comment by stephentoub** [comment]
> Before the change we were getting curl exceptions saying it got an empty response from the server.

Are you sure its not an issue with the server? From a quick glance at the change, the biggest difference is the former is using a single HttpClient whereas the latter is using one per request, which means the former is using connection pooling whereas the latter isn't.

**Comment by cesarbs** [comment]
Debugging this and got this:

    Microsoft.AspNetCore.Server.Kestrel.Networking.UvException: Error -40 EMSGSIZE message too long
    fail: Microsoft.AspNetCore.Server.Kestrel[0]
          DispatchPipe.ReadStart

Seems like a problem in Kestrel indeed.

**Comment by mikeharder** [comment]
So this isn't related to the open file limit at all?

**Comment by cesarbs** [comment]
@mikeharder I don't want to say it's 100% not at this point, but I don't think so. I was watching the number of file descriptors used by the process and it never went above the limit.

**Comment by halter73** [comment]
@cesarbs Do you think we should close this?

**Comment by cesarbs** [comment]
@halter73 Yeah.

**Pull request closed without merging**
