### PR TITLE
Mono not happy with client keep-alive header

### PR DESCRIPTION
**Pull request by benaadams**
*edit*
Moved test to correct place; to correctly test without relying on "keep-alive" behaviour of the client.

### CODE REVIEW

**Comment by cesarbs** [comment]
Can you elaborate a little on this? Did you find any indications of why this is happening?

**Comment by halter73** [comment]
Does this mean HttpClient is sometimes making all the requests on seperate connections on Mono? It might be best to have this as an `EngineTest` so we can be sure all requests are made on the same socket.

**Comment by benaadams** [comment]
Not sure, isn't all the time; but enough to be annoying; and not always being Keep-alive isn't necessarily wrong; but bad for the test as it stands.

@halter73 yea; will move to `EngineTest` sounds like a good idea

**Comment by benaadams** [comment]
@cesarbs this should fix the mono ci issues - if it doesn't cause hangs :P

**Comment by benaadams** [comment]
Ignoring nuget being unhappy

**Comment by halter73** [comment]
:shipit:

**Comment by cesarbs** [comment]
:+1:

**Pull request merged**
