### PR TITLE
Merge/release/2.1 to release/2.2

### PR DESCRIPTION
**Pull request by natemcmaster**
Notably, includes @halter73's change to merge BufferWriter and CountingBufferWriter and #2717.

See also https://github.com/aspnet/Common/pull/390

### CODE REVIEW

**Comment by natemcmaster** [comment]
Are test failures on VSTS a known issue? Tests in VSTS failed for Windows and Linux.

**Comment by natemcmaster** [comment]
image

**Comment by natemcmaster** [comment]
:bell:

**Comment by natemcmaster** [comment]
It looks like Kestrel has only passed once on VSTS in the last few weeks. I'm going to just disable that PR check since something is clearly going wrong.

image

**Comment by pakrym** [comment]
Wait.

**Pull request merged**
