### PR TITLE
Measure Writing in FrameWritingBenchmark

### PR DESCRIPTION
**Pull request by benaadams**
Wasn't really measuring the actual writing path before
Also was incorrectly measuring sync vs async by adding an additional await in the async path

/cc @davidfowl

### CODE REVIEW

**Comment by benaadams** [comment]
Output (minus StdDev, Median)
```
     Method | WithHeaders | Chunked | OnStarting |        Mean |       Op/s | Allocated |
----------- |------------ |-------- |----------- |------------ |----------- |---------- |
 WriteAsync |       False |   False |      Async | 138.8264 ns | 7203239.23 |      78 B |
 WriteAsync |       False |   False |       None | 139.5984 ns | 7163404.47 |      78 B |
 WriteAsync |       False |   False |       Sync | 142.2543 ns | 7029662.80 |      78 B |
 WriteAsync |       False |    True |      Async | 140.8392 ns | 7100294.58 |      78 B |
 WriteAsync |       False |    True |       None | 140.9036 ns | 7097048.48 |      78 B |
 WriteAsync |       False |    True |       Sync | 140.8301 ns | 7100756.97 |      78 B |
 WriteAsync |        True |   False |      Async | 635.7148 ns | 1573032.43 |     306 B |
 WriteAsync |        True |   False |       None | 527.2127 ns | 1896767.50 |     178 B |
 WriteAsync |        True |   False |       Sync | 632.5463 ns | 1580911.93 |     306 B |
 WriteAsync |        True |    True |      Async | 629.4966 ns | 1588570.92 |     306 B |
 WriteAsync |        True |    True |       None | 524.1801 ns | 1907741.15 |     178 B |
 WriteAsync |        True |    True |       Sync | 632.1967 ns | 1581786.05 |     306 B |
 ```

**Comment by davidfowl** [comment]
@pakrym Does this look ok to you?

**Comment by muratg** [comment]
*ping* @pakrym

**Comment by pakrym** [comment]
Closing, please reopen if we are going to do performance work in this area.

**Pull request closed without merging**
