### PR TITLE
Add ServiceContext to make it easier to flow new services through ctors

### PR DESCRIPTION
**Pull request by halter73**

### CODE REVIEW

**Comment by davidfowl** [comment]
Why is appveyor failing all of a sudden?

**Comment by halter73** [comment]
@davidfowl Your comment implies appveyor was passing before...

https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/history

**Comment by davidfowl** [comment]
:shipit:

**Comment by lodejard** [comment]
:shipit:

**Comment by halter73** [comment]
Here's the commit: https://github.com/aspnet/KestrelHttpServer/commit/f10c989d9034e8cc830db7a4a18008be3b3f84ab

**Pull request closed without merging**
