### PR TITLE
Use Unsafe.Read<> for faster Vector ctors

### PR DESCRIPTION
**Pull request by benaadams**
Needs `System.Runtime.CompilerServices.Unsafe` added to feed

Also using Vector for validation of longer headers which is good for `Content-Security-Policy` and `Cookie`

### CODE REVIEW

**Comment by halter73** [comment]
Cool PR. I didn't know about the `System.Runtime.CompilerServices.Unsafe` package. [Here is a branch](https://github.com/aspnet/KestrelHttpServer/blob/halter73/benchmark-validate-header/samples/Benchmark/Program.cs) I used to compare different `ValidateHeaderCharacters` implementations.

I had a somewhat similar implementation (TestValidateHeaderValues3) to yours (TestValidateHeaderValues5) that is much slower since it uses `ToCharArray` and `Buffer.BlockCopy`.

Here are the results I got when testing against all the fake header values:

```ini

BenchmarkDotNet=v0.9.4.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz, ProcessorCount=4
Frequency=2435884 ticks, Resolution=410.5286 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1078.0

Type=Program  Mode=Throughput

```
                    Method |      Median |     StdDev |
-------------------------- |------------ |----------- |
 TestValidateHeaderValues1 |  66.4891 us |  3.0924 us |
 TestValidateHeaderValues2 |  84.8861 us |  2.1947 us |
 TestValidateHeaderValues3 | 161.7872 us | 10.0224 us |
 TestValidateHeaderValues4 |  69.0152 us |  4.5343 us |
 TestValidateHeaderValues5 |  40.8759 us |  2.1885 us |

Here are the results I got when removing the three largest header values:

```ini

BenchmarkDotNet=v0.9.4.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz, ProcessorCount=4
Frequency=2435884 ticks, Resolution=410.5286 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1078.0

Type=Program  Mode=Throughput

```
                    Method |        Median |      StdDev |
-------------------------- |-------------- |------------ |
 TestValidateHeaderValues1 |   569.0469 ns |  53.4758 ns |
 TestValidateHeaderValues2 |   658.3479 ns |  29.6889 ns |
 TestValidateHeaderValues3 | 3,111.6132 ns | 533.1012 ns |
 TestValidateHeaderValues4 |   549.9138 ns |  55.9223 ns |
 TestValidateHeaderValues5 |   384.3479 ns |  45.7377 ns |

**Comment by halter73** [comment]
You're right that we should wait to get `System.Runtime.CompilerServices.Unsafe` pushed to our MyGet. Once we do that I would like to see this split into two commits. One to update our Seek methods (a benchmark for that would be great too if you could provide it), and one to update `ValidateHeaderCharacters`. It probably also nice to use `if (Vector.IsHardwareAccelerated)` in `ValidateHeaderCharacters` for consistency even though it isn't the major issue it once was.

**Comment by benaadams** [comment]
> I didn't know about the System.Runtime.CompilerServices.Unsafe package

I think it only appeared 2 days ago :)

**Comment by benaadams** [comment]
Closing and have split to https://github.com/aspnet/KestrelHttpServer/pull/811 and https://github.com/aspnet/KestrelHttpServer/pull/812

**Pull request closed without merging**
