### PR TITLE
Handle SocketError.ProtocolType as a connection reset on macOS

### PR DESCRIPTION
**Pull request by halter73**
Backport of #2845

Addresses #2885

### CODE REVIEW

**Comment by Tratcher** [comment]
Didn't need this bit? https://github.com/aspnet/KestrelHttpServer/pull/2845/files#diff-a538265cafcdc8078989d06b998e6fb9R342

**Comment by halter73** [comment]
Since is a 2.1 backport, and src changes are difficult to get approval for to begin with, I'm trying to make this as surgical as possible.

**Comment by halter73** [comment]
@muratg @Eilon What do I need to do to get this approved for 2.1? It's a src change, but a very safe/minor one.

See https://github.com/aspnet/KestrelHttpServer/issues/2885#issuecomment-420431891 for context

**Comment by Eilon** [comment]
What @muratg said.

**Comment by halter73** [comment]
I agree that changing Sockets is a better change. I think the only way to avoid test failures in 2.1 without a product change such as this is to skip all of our connection reset functional tests on macOS in release/2.1. Should we do that instead?

**Comment by muratg** [comment]
@halter73 yeah, I think that's the best we can do. We'd get coverage from Windows and Linux runs. And we _know_ the reason for the MacOS failures so let's just skip those.

**Pull request closed without merging**
