### PR TITLE
 Improve MaxRequestBufferSizeTests reliability

### PR DESCRIPTION
**Pull request by halter73**

### CODE REVIEW

**Comment by Tratcher** [comment]
Still failed on at least one of the CIs.

**Comment by pakrym** [comment]
This test fails on OSX

**Comment by mikeharder** [comment]
@halter73: Close as dup of https://github.com/aspnet/KestrelHttpServer/commit/1951ddf6eadc828f05eb69bf13f94b5bda4d8388?

**Comment by halter73** [comment]
Yep. Thanks

**Pull request closed without merging**
