### PR TITLE
Move non-nested classes and interfaces to their own files

### PR DESCRIPTION
**Pull request by halter73**
- Ensure all the C# files have copyright notices

### CODE REVIEW

**Comment by davidfowl** [comment]
Finally 😀

**Comment by davidfowl** [comment]
:shipit:

**Comment by Tragetaschen** [comment]
If there's any interest in #60, then these kinds of changes make it hard to maintain it on top of dev.

**Comment by davidfowl** [comment]
@Tragetaschen I would close 60 TBH, there are too many changes. It would be great it you worked with @halter73 to integrate what you think make sense in a more piece meal manner.

**Comment by Tragetaschen** [comment]
Yeah, I figured this would happen a long time ago. `cherry-pick` ftw

It's great to see Kestrel finally gets some attention!

**Pull request closed without merging**
