### PR TITLE
Short folder names

### PR DESCRIPTION
**Pull request by natemcmaster**
As long as we are rearranging out entire codebase...

https://github.com/aspnet/KestrelHttpServer/tree/namc/folders

image

image

### CODE REVIEW

**Comment by pakrym** [comment]
I think if we should do it only if it's going to be done for entire asp.net core. Also not before @halter73 change gets merged.

**Comment by natemcmaster** [comment]
To be clear, there are no plans to do it for all of aspnet core, but I don't think that should stop us from using a cleaner layout. There is at least [one other repo](https://github.com/aspnet/EntityFramework/tree/dev/src) that has already done this.

Btw, this is on top off @halter73's change.

**Comment by cesarbs** [comment]
Farewell GitHub history 😝

**Comment by cesarbs** [comment]
Not entirely opposed to the change but let's first get the new packages' names right (`*.Transport.*`)

**Comment by natemcmaster** [comment]
So, this?
```
- src/
  + Kestrel
  + Kestrel.Core
  + Kestrel.Transport.Libuv
  + Kestrel.Https
```

In the future we can add Kestrel.Transport.(Whatever).

> Farewell GitHub history 

Yeah :-/. We're gonna lose it no matter what in https://github.com/aspnet/KestrelHttpServer/pull/1551. If only there was [some way](https://git-scm.com/docs/git-log#git-log---follow) to follow git renames. :trollface:

**Comment by davidfowl** [comment]
I'm going to say no to this since it's inconsistent I also prefer the long names. Get the github expander plugin.

**Comment by davidfowl** [comment]
I also adds no value and history ends up being messed up for no good reason (and yes, GitHub should fix their CSS 🤣)

**Comment by davidfowl** [comment]
I also agree with Pavel, if we're not doing this for all of ASP.NET Core it's pointless. Consistency is good across repos and EF for tend to be a bit different with some things done in the repo.

**Comment by natemcmaster** [comment]
@davidfowl has had a change of heart.

**Comment by pakrym** [comment]
Are we doing it for all repos?

**Comment by Tratcher** [comment]
This kind of structure should be consistent across repos. All or none...

I can only assume this breaks some tooling regexes..

**Comment by natemcmaster** [comment]
FYI all - details begin discussed internally, but the primary motivation is continual problems with filenames that grow beyond max path issues. Not sure yet if all repos will get this treatment or not, but regardless, I want this for Kestrel as this project has particularly long filenames, eg `src/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csproj`

**Comment by natemcmaster** [comment]
:watch: waiting until the work on rel/2.0.0 is done. This would make it painful to merge changes in rel/2.0.0 back to dev.

**Pull request merged**
