### PR TITLE
Don't reset frame state when connection is aborted (#1103).

### PR DESCRIPTION
**Pull request by cesarbs**
See https://github.com/aspnet/KestrelHttpServer/issues/1103#issuecomment-250237677.

- [x] TODO: add tests.

cc @halter73 @mikeharder @davidfowl

### CODE REVIEW

**Comment by cesarbs** [comment]
Wondering if this is the best fix. Setting `PrepareRequest` to null in `Frame.Abort()` might be better. Thoughts?

**Comment by halter73** [comment]
We call Reset() at the end of the loop instead of the beginning to avoid rooting strings and maybe a few other things between requests and when the connection is idle.

I think the more general purpose change might be just to do `if (!_requestProcessingStopping) Reset()`. This covers both the aborted and request rejected cases.

**Comment by cesarbs** [comment]
@halter73 Changed to `Reset()` on `!_requestProcessingStopping`.

**Comment by cesarbs** [comment]
Added test.

**Comment by halter73** [comment]
:shipit:

**Pull request merged**
