### PR TITLE
Increase .travis.yml consistency between repos

### PR DESCRIPTION
**Pull request by dougbu**
- aspnet/Universe#349
- minimize `dotnet` setup time; no need for caching
- install packages used in other repos; explicit and avoids issues as (Beta) Trusty image changes

### CODE REVIEW

**Comment by dougbu** [comment]
First run of this PR failed on OSX but that's consistent w/ recent `dev` builds in this repo. E.g. https://travis-ci.org/aspnet/KestrelHttpServer/jobs/157157166 also ended w/ the following error:
```
fail: Block being leased from disposed pool!
fail:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
fail:    at System.Environment.get_StackTrace()
fail:    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
fail:    at System.Diagnostics.Debug.Assert(Boolean condition, String message)
fail:    at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPool.Lease(String memberName, String sourceFilePath, Int32 sourceLineNumber) in /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/MemoryPool.cs:line 74
```

**Comment by benaadams** [comment]
Secondary effect from startup failure
```
info:       System.AggregateException : One or more errors occurred. (Error -16 EBUSY resource busy or locked)
info:       ---- Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException : Error -16 EBUSY resource busy or locked
```

**Comment by dougbu** [comment]
I'm not sure @benaadams.

I've done 3 builds of my Kestrel branch on OSX and all failed after a `Block being leased from disposed pool!`. The `AggregateException` you mention was part of the failure in 2 of the 3 runs (not the first time). Unfortunately I didn't download the logs of the earlier two runs.

For those playing along at home, the latest failure is at https://travis-ci.org/aspnet/KestrelHttpServer/jobs/157524942

**Comment by benaadams** [comment]
Do you not have any other errors in the logs? There is definitely an exception path that doesn't return the block so the finalizer picks it up and throws this error - however it generally seems to be coupled with another error.

**Comment by dougbu** [comment]
Raw log attached.
[log.txt](https://github.com/aspnet/KestrelHttpServer/files/454208/log.txt)

In any case, I can't imagine these failures have anything to do w/ the minor `.travis.yml` change in this PR. Looks like an existing issue. Is someone working to clean the OSX builds up?

**Comment by benaadams** [comment]
Likely https://github.com/aspnet/KestrelHttpServer/issues/1078 and https://github.com/aspnet/KestrelHttpServer/issues/1079

**Comment by dougbu** [comment]
4dc2a38

**Pull request closed without merging**
