### PR TITLE
Update to version 1.1.1.

### PR DESCRIPTION
**Pull request by cesarbs**
Again, just want some 👀 on it.

@pranavkm @Eilon @muratg @halter73 @pakrym

### CODE REVIEW

**Comment by cesarbs** [comment]
We don't have a `rel/1.1.0` branch (only tag) and GitHub only accept base branches for diff.

**Comment by Tratcher** [comment]
Just create the rel/1.1.1 branch at the rel/1.1.0 tag.

**Comment by cesarbs** [comment]
@Tratcher Do you mean a `rel/1.1.0` branch so we have parity?

**Comment by cesarbs** [comment]
@Tratcher Got what you meant. Created.

**Comment by cesarbs** [comment]
🔔

**Pull request merged**
