### PR TITLE
ConcurrentStack -> ConcurrentQueue

### PR DESCRIPTION
**Pull request by benaadams**
Stack to Queue test by @NickCraver https://twitter.com/Nick_Craver/status/665503509958258688

### CODE REVIEW

**Comment by NickCraver** [comment]
+1 - `ConcurrentQueue` should be (and is measured to be) faster at higher mixed workloads and we have a 1:1 here. 

Reference for the curious: http://blogs.msdn.com/b/pfxteam/archive/2010/04/26/9997562.aspx

**Comment by benaadams** [comment]
ConcurrentBag might work here; its a memory pig though :(

**Comment by lodejard** [comment]
Isn't it better to provide the most-recently-returned block, rather than provide the least-recently-used block, when someone asks for memory? That's why it was a stack instead of a queue in the first place

**Comment by benaadams** [comment]
The issue is caused by contention by both [readers](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs#L292) and [writers](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs#L488) on the `_head` with a `ConcurrentStack` so when it hits high throughput the Interlocked fails and it moves to burning cpu with [`PushCore`](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs#L380) and [`TryPopCore`](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentStack.cs#L603) in cpu spins - though it will always make forward progress.

With `ConcurrentQueue` it [enqueues to tail and dequeues from tail](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentQueue.cs#L534) which are different locations so writes only contend with writes and reads only contend with reads.

Also it allocates individual Nodes for every push vs `ConcurrentQueue` using array chunks and reusing them; so allocating less.

**Comment by benaadams** [comment]
Though something to measure (perhaps after the other changes to up throughput)

@NickCraver saw an increase from 931,289.67 RPS to 1,191,674.89 RPS when this was added on top of the other changes.

**Comment by rynowak** [comment]
If contention on the memory pool is having this much of an impact on perf, it might be worth investigating if round-distributing to separate pools is an improvement.

**Comment by benaadams** [comment]
@rynowak I push them out so each `KestrelThread` has there own pool in this PR https://github.com/aspnet/KestrelHttpServer/pull/343/files#diff-2ee816fea70408fbc7f21874eccb9211R35 also so they can be disposed.

**Comment by lodejard** [comment]
Okay, reducing push/pull contention sounds like a reasonable cause for the change. 

Doesn't each thread already have it's own pool2?

**Comment by lodejard** [comment]
Well - each uv loop more than each thread. The fact that some of the work is done on worker threads means the pool isn't truly isolated to the loop

**Comment by benaadams** [comment]
> Doesn't each thread already have it's own pool2?

PRs not been merged yet ;-)

**Pull request merged**
