### PR TITLE
WIP Revert https://github.com/aspnet/KestrelHttpServer/pull/2502

### PR DESCRIPTION
**Pull request by JunTaoLuo**
The performance regression may be too significant. See https://github.com/aspnet/Benchmarks/issues/569. cc @muratg @Eilon: @davidfowl wanted to potentially revert this for 2.2.

### CODE REVIEW

**Comment by Eilon** [comment]
The benchmark issue is comparing 2.2 preview1 and 2.2 preview2. What's up with that? @sebastienros

**Comment by JunTaoLuo** [comment]
The changes we made went into preview2. So the benchmarks are essentially testing without and with the 0-byte read changes.

**Comment by sebastienros** [comment]
I don't know, maybe related to https://github.com/aspnet/Benchmarks/issues/569

**Comment by JunTaoLuo** [comment]
FYI, this is still not committed to being reverted, but I figured I'll prepare the PR first in case we decide to take it. Looking into test failures now.

**Comment by JunTaoLuo** [comment]
Preliminary numbers suggest we'd want to take https://github.com/aspnet/KestrelHttpServer/pull/3094 instead.

**Pull request closed without merging**
