### PR TITLE
[Exploritory] Relayer

### PR DESCRIPTION
**Pull request by benaadams**
Still needs work

### CODE REVIEW

**Comment by benaadams** [comment]
I think next step would be ServiceContext being a Kestrel thing so coming out of Connection

**Comment by davidfowl** [comment]
`Frame` : `ServiceContext` looks problematic,

**Comment by benaadams** [comment]
In ServiceConext is a lot of http specific stuff rather than networking

These might be valid for networking
```csharp
public IApplicationLifetime AppLifetime { get; set; }
public IConnectionTrace Log { get; set; }
public IThreadPool ThreadPool { get; set; }
```
This is probably split (e.g. `NoDelay`)
```csharp
public KestrelServerOptions ServerOptions { get; set; }
```
These are very much not Connection related
```csharp
public DateHeaderValueManager DateHeaderValueManager { get; set; }
public IHttpComponentFactory HttpComponentFactory { get; set; }
public Func<IConnectionContext, Frame> FrameFactory { get; set; }
public Action<IFeatureCollection> PrepareRequest { get; set; }
```

**Comment by benaadams** [comment]
Reverting the ServiceConext thing but FrameFactory can be `Func<IConnectionContext, IFrameControl>` if the methods Start, Stop and Abort are added to it.

**Comment by benaadams** [comment]
Better?

**Comment by benaadams** [comment]
Better? ComponentFactory crosses the line; but its an idea

**Comment by benaadams** [comment]
Going to leave it alone now :)

**Comment by benaadams** [comment]
Closing :)

**Pull request closed without merging**
