### PR TITLE
Xmas combo

### PR DESCRIPTION
**Pull request by benaadams**
Best yet... (though will probably have to break it down into pieces?)

Azure G4 Peaking 2.7 GBps send 1.1GBps receive

344,334 rps Non pipelined w/ 3.44ms latency (32 threads and 1024 connections)
2,398,936 rps 16 pipelined w/ 5.66ms latency (32 threads and 1024 connections)

(3.9 - 4.2 Gbps send / 1.4 - 1.5 Gbps receive when pipelined 512)

### CODE REVIEW

**Comment by benaadams** [comment]
> Running 30s test @ http://.../plaintext
  32 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.50ms   16.64ms 288.14ms   96.96%
    Req/Sec    75.44k     7.43k  183.60k    86.71%
  69929367 requests in 30.08s, 8.60GB read
  Socket errors: connect 35, read 0, write 0, timeout 0
Requests/sec: 2324948.53
Transfer/sec:    292.68MB

**Comment by benaadams** [comment]
> Running 30s test @ http://..../plaintext
  32 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.66ms   13.27ms 366.96ms   97.21%
    Req/Sec    77.84k     7.30k  172.61k    82.76%
  72158246 requests in 30.08s, 8.87GB read
  Socket errors: connect 35, read 0, write 0, timeout 0
Requests/sec: 2398936.64
Transfer/sec:    301.99MB

**Comment by cesarbs** [comment]
This is a lot in a single PR. Is it all really part of the same change or could you break this up into multiple PRs?

**Comment by benaadams** [comment]
I think its more of a journey that a PR :)

I should be able to split it in to separate PRs though have some of them build of a merge of another?

e.g. Only pooled blocks -> Expose pointer -> Removed fixed (in lots of places)

**Comment by benaadams** [comment]
> Running 30s test @ http://.../plaintext
  32 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.63ms   12.10ms 406.38ms   96.73%
    Req/Sec    77.37k     7.53k  258.40k    86.85%
  74024392 requests in 30.10s, 9.10GB read
Requests/sec: 2459192.17
Transfer/sec:    309.58MB

**Comment by benaadams** [comment]
Not sure about last one, but...
> Running 30s test @ http://..../plaintext
  32 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.68ms   17.92ms 353.24ms   96.80%
    Req/Sec    78.43k     7.62k  146.88k    83.62%
  75113786 requests in 30.10s, 9.23GB read
Requests/sec: 2495536.14
Transfer/sec:    314.15MB

**Comment by benaadams** [comment]
256 latency is crazy
>Running 30s test @ http://.../plaintext
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.49ms    5.73ms 211.36ms   88.81%
    Req/Sec    78.07k     6.52k  151.92k    80.45%
  74725034 requests in 30.10s, 9.19GB read
Requests/sec: 2482757.39
Transfer/sec:    312.54MB

**Comment by benaadams** [comment]
smurf-testing

**Comment by benaadams** [comment]
> Running 1m test @ http://.../plaintext
  32 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.09ms   12.34ms 310.39ms   97.63%
    Req/Sec    86.81k     7.82k  170.18k    79.29%
  160832007 requests in 1.00m, 19.77GB read
  Socket errors: connect 35, read 0, write 0, timeout 0
Requests/sec: 2676090.47
Transfer/sec:    336.88MB

with https://github.com/aspnet/Common/pull/74 and https://github.com/aspnet/HttpAbstractions/pull/521

**Comment by benaadams** [comment]
> Running 1m test @ http://.../plaintext
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.20ms    4.92ms 228.28ms   91.26%
    Req/Sec    87.25k     6.86k  144.16k    76.85%
  166848206 requests in 1.00m, 20.51GB read
Requests/sec: 2776712.83
Transfer/sec:    349.55MB

**Comment by benaadams** [comment]
> Running 1m test @ http://.../plaintext
  32 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.82ms   12.41ms 281.62ms   97.75%
    Req/Sec    89.63k    16.84k  179.39k    91.52%
  171131325 requests in 1.00m, 21.04GB read
  Socket errors: connect 35, read 0, write 0, timeout 0
Requests/sec: 2848191.98
Transfer/sec:    358.54MB

**Comment by benaadams** [comment]
> Running 1m test @ http://.../plaintext
  32 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.82ms   12.41ms 281.62ms   97.75%
    Req/Sec    89.63k    16.84k  179.39k    91.52%
  171131325 requests in 1.00m, 21.04GB read
  Socket errors: connect 35, read 0, write 0, timeout 0
Requests/sec: 2848191.98
Transfer/sec:    358.54MB

> Running 1m test @ http://.../plaintext
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.12ms    3.71ms 209.34ms   89.65%
    Req/Sec    90.31k     6.54k  135.20k    76.12%
  172694464 requests in 1.00m, 21.23GB read
Requests/sec: 2874816.92
Transfer/sec:    361.90MB

**Comment by halter73** [comment]
Is there any particular reason that the ValueTask inclusion didn't make the combo?

**Comment by benaadams** [comment]
@halter73 not really :)

There is a change to OutputSocket in this that is a little dodgy; sometimes good for throughput sometimes really bad. Have to rework it.

**Comment by halter73** [comment]
@benaadams Since we've split this into smaller PRs, are we OK to close this now?

**Comment by benaadams** [comment]
Yeah; though is a bunch more it this that I haven't done PRs for; but I'll remember them.

**Pull request closed without merging**
