### PR TITLE
More specific response status codes for errors (#653)

### PR DESCRIPTION
**Pull request by cesarbs**
#653 

@halter73 @mikeharder @Tratcher @davidfowl

### CODE REVIEW

**Comment by cesarbs** [comment]
Want to get this in before https://github.com/aspnet/KestrelHttpServer/pull/1111 so I can return 408 on timeouts.

**Comment by halter73** [comment]
So the new status codes are 414, 431 and 505. Is that it? It would be nice to include that in the commit message.

**Comment by cesarbs** [comment]
@halter73 Updated commit message.

**Comment by cesarbs** [comment]
Since I had to touch them, I've changed `MaxRequestLineSizeTests` and `RequestHeaderLimitsTests` to use `TestServer`.

**Pull request merged**
