### PR TITLE
Execute `dnu restore` in Travis builds with .NET Core

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by davidfowl** [comment]
@dougbu I think it's time to turn this on by default again.

**Comment by dougbu** [comment]
@davidfowl I'm working toward that but avoiding a big-bang upgrade. Will do a few repos at a time now that I can switch them over individually.

**Comment by dougbu** [comment]
... also, was your comment shaped like a squirrel?

**Comment by dougbu** [comment]
:up::date: (very slight update)

**Pull request merged**
