### PR TITLE
Removed IsLocal from ConnectionInfo

### PR DESCRIPTION
**Pull request by BrennanConroy**
https://github.com/aspnet/HttpAbstractions/issues/536
@halter73 @Tratcher

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Need to update this still, wait a couple mins

**Comment by muratg** [comment]
What else needs changing here?

**Comment by BrennanConroy** [comment]
Needed to remove another IsLocal from HttpConnectionFeature, now it should be good. Won't pass on Travis

**Comment by Tratcher** [comment]
:shipit:

**Comment by halter73** [comment]
:ship:

**Pull request merged**
