### PR TITLE
Remove rogue ConfigureAwait

### PR DESCRIPTION
**Pull request by davidfowl**
- We don't do it anywhere else, I assume this is left over
from older legacy

### CODE REVIEW

**Comment by benaadams** [comment]
Is because it's calling user code and who knows what they may do?

**Comment by davidfowl** [comment]
@benaadams so does https://github.com/aspnet/KestrelHttpServer/blob/557c04c93295d7c6965618eaa66ed9725343af0f/src/Microsoft.AspNetCore.Server.Kestrel.Core/Internal/Http/FrameOfT.cs#L129 and https://github.com/aspnet/KestrelHttpServer/blob/557c04c93295d7c6965618eaa66ed9725343af0f/src/Microsoft.AspNetCore.Server.Kestrel.Core/Internal/Http/FrameOfT.cs#L136

**Comment by benaadams** [comment]
That's all I've got :)

**Comment by benaadams** [comment]
Guessing it doesn't matter as its the outer await that calls user code; rather than an inner one user code calls. Bit early an not had coffee yet :)

**Comment by davidfowl** [comment]
> Actually can you still specify the scheduler stuff gets run on? Might be more important now?
Yes, it'll be fun to see what people come up with (by shooting themselves in the foot 😄 ). We need to make sure everything runs properly when you run on IO threads if you don't do anything wrong. 

@cesarbs already found a problem https://github.com/aspnet/KestrelHttpServer/pull/1829

**Pull request merged**
