### PR TITLE
Make the CI build work

### PR DESCRIPTION
**Pull request by benaadams**
Resolve compile warnings
Always shutdown

### CODE REVIEW

**Comment by benaadams** [comment]
Server should always shut down after last commit in this 

/cc @cesarbs @halter73

**Comment by benaadams** [comment]
Crazy town! Lights are green! --> https://github.com/aspnet/KestrelHttpServer/pull/635

**Comment by cesarbs** [comment]
@halter73 has the proper fix here: https://github.com/aspnet/KestrelHttpServer/commit/7455e11b82e95175f157733219b82be84f34e0b8

**Comment by halter73** [comment]
I'm fairly certain the CI hangs are fixed by [this commit](https://github.com/aspnet/KestrelHttpServer/commit/7455e11b82e95175f157733219b82be84f34e0b8). That's why I removed the same FrameworkSkipConditions in #623. The commit message should explain why the fix makes the second call to `uv_run` terminate reliably.

I think this is a more appropriate than setting the `IsBackground` property on the thread.

**Comment by benaadams** [comment]
Is obviously better to have the cause dealt with rather than just the symptom :)

Might be worth still adding the the `IsBackground = false` for `#if !DEBUG`? So issues still get seen for testing but always stops in production (with the actual good clean up code in #623)

**Comment by halter73** [comment]
I think the `#if !DEBUG` thing is a good idea.

**Comment by benaadams** [comment]
Want to add it to #623? Will close this and the other one.

**Comment by halter73** [comment]
Will do

**Pull request closed without merging**
