### PR TITLE
Use TaskCache class from Microsoft.Extensions.TaskCache.Sources

### PR DESCRIPTION
**Pull request by pakrym**
Instead of Task.FromResult(0)

@cesarbs @halter73

### CODE REVIEW

**Comment by benaadams** [comment]
> error CS0433: The type 'TaskCache' exists in both 'Microsoft.AspNetCore.Server.Kestrel.Https, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Server.Kestrel, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by rynowak** [comment]
using `[InternalsVisibleTo]` in product code? FOR SHAME

**Comment by pakrym** [comment]
Travis failure seems unrelated to the change.

**Comment by cesarbs** [comment]
@pakrym Yeah I'm investigating that.

**Comment by halter73** [comment]
`[InternalsVisibleTo]` is used a bit for the unit test project to access special test only ctors.

**Comment by halter73** [comment]
:shipit:

**Pull request merged**
