### PR TITLE
Use pass through connection adapter instead of ssl for max buffer size tests

### PR DESCRIPTION
**Pull request by pakrym**
@halter73

### CODE REVIEW

**Comment by cesarbs** [comment]
cc @mikeharder who authored that test.

**Comment by cesarbs** [comment]
What is the reason for the change?

**Comment by pakrym** [comment]
It hangs :) I think it's because we stopped posting `Pause` and `Resume` so when buffer size threshold is hit connection is paused immediately vs having it posted and allowing another read to pass through.

**Comment by pakrym** [comment]
:up::date:

**Comment by halter73** [comment]
:shipit:

**Pull request merged**
