### PR TITLE
Ensure clients connecting to Kestrel's dispatch pipe are listeners (rel/1.0.2)

### PR DESCRIPTION
**Pull request by halter73**
rel/1.0.2 version of https://github.com/aspnet/KestrelHttpServer/pull/1206

Restore still seems to still be failing in rel/1.0.2.

### CODE REVIEW

**Comment by cesarbs** [comment]
Have you tested it on Azure (this version)?

**Comment by cesarbs** [comment]
I think you need to open a 1.0.2-specific issue.

**Comment by halter73** [comment]
I just now built this branch on my machine by changing the dependencies to "-rtm-*" so they could be downloaded from aspnetcore-rel-1-0-3 myget feed. I will test this version on Antares soon.

I created a rel/1.0.2 issue at https://github.com/aspnet/KestrelHttpServer/issues/1208

**Comment by halter73** [comment]
Tested on Antares. Looking good.

**Pull request merged**
