### PR TITLE
Stub out IServer.Dispose

### PR DESCRIPTION
**Pull request by Tratcher**
https://github.com/aspnet/Hosting/pull/995

This is a minimal implementation of the interface that achieves the basic behavior (gracefully stopping the server). I'll file a followup issue to separate out Dispose as an abortive shutdown.

### CODE REVIEW

**Comment by davidfowl** [comment]
You'll need to wait on @halter73 's refactoring before we do anything here.

**Comment by davidfowl** [comment]
Yes, nobody should be checking in anything until @halter73 is done.

**Comment by davidfowl** [comment]
@Tratcher are you going to rebase this?

**Comment by muratg** [comment]
@Tratcher close?

**Pull request closed without merging**
