### PR TITLE
Added some KestrelServer tests

### PR DESCRIPTION
**Pull request by khellang**
As discussed with @halter73 in #457 :sparkles:

### CODE REVIEW

**Comment by khellang** [comment]
Looks like Travis is stuck :confounded: https://travis-ci.org/aspnet/KestrelHttpServer/pull_requests

**Comment by muratg** [comment]
Yeah, it seems queue is still not done.  @Eilon do we have a way to empty the Travis build queue?

**Comment by muratg** [comment]
Great negative tests BTW, thanks!

**Comment by cesarbs** [comment]
:+1:

**Comment by Eilon** [comment]
@BrennanConroy was going to contact Travis support. Nothing I can see on the admin side.

**Comment by halter73** [comment]
Thanks! I hope you succeed with your 24 pull requests :wink:

**Pull request merged**
