### PR TITLE
Removed automatic Upgrade header logic from UpgradeAsync (#2086).

### LINKED ISSUE #2086: Remove automatic Upgrade header logic from UpgradeAsync
https://github.com/aspnet/KestrelHttpServer/blob/a31d1e024ca86a4a9053e0be105fde17c5ccae10/src/Kestrel.Core/Internal/Http/Http1Connection.FeatureCollection.cs#L42-L50
This code copies the request Upgrade header to the response. However, the request Upgrade header is a list of suggestions, while the response is the ordered list of actually selected protocols. Setting any of these response headers is the caller's responsibility. The WebSocket middleware sets these.
https://github.com/aspnet/WebSockets/blob/31c1e9d7d727fda23ae657cb3598c7c3f3950d15/src/Microsoft.AspNetCore.WebSockets/Internal/HandshakeHelpers.cs#L66-L75

https://tools.ietf.org/html/rfc7230#section-6.7

This method is also missing a HasResponseStarted check. It will fail only when it tries to set the StatusCode.

### PR DESCRIPTION
**Pull request by markuspalme**
Fixes #2086.

### CODE REVIEW

**Comment by markuspalme** [comment]
Will get to those tests tomorrow.

**Comment by muratg** [comment]
@markuspalme thanks for the contribution!  Are you still looking into this?

**Comment by markuspalme** [comment]
@muratg Sorry for the late response. I could not look into this, but am not sure this is needed any more because of PR #2329.

**Comment by davidfowl** [comment]
Will close this out

**Pull request closed without merging**
