### PR TITLE
Allocate DateHeaderValueManager byte array only once.

### PR DESCRIPTION
**Pull request by cesarbs**
Small thing but avoids an allocation every second. That repeated allocation is not necessary since the date always has the same number of characters (format is `ddd, dd MMM yyyy HH:mm:ss GMT`).

cc @halter73 @mikeharder @davidfowl

### CODE REVIEW

**Comment by benaadams** [comment]
Torn reads? What happens if its read while being written?

**Comment by cesarbs** [comment]
It's read via `_dateValues`, which is a new instance created after the data is in `_dateBytes`.

**Comment by cesarbs** [comment]
@benaadams :sob: I guess I could lock but not sure we'd want that vs. allocating.

**Comment by benaadams** [comment]
Is only 29 (+ 12?) bytes a second :smile:  

Isn't like its 88 bytes a request or 176 MB/s https://github.com/aspnet/HttpAbstractions/issues/677 at @ 2Mrps :trollface:

**Pull request closed without merging**
