### PR TITLE
Improve perf by not taking SocketOutput._contextLock when copying buffers

### PR DESCRIPTION
**Pull request by halter73**
The downside is that calls to `SocketOutput.WriteAsync` are no longer "atomic" when called concurrently, but I would argue that `Response.WriteAsync` shouldn't be called concurrently.

After seeing the performance improvement that could be achieved in #1148 by taking the `_contextLock` less, I decided to try to improve perf by not taking SocketOutput._contextLock when copying buffers. I had this idea before, but the improvement now seems to be measurable on better hardware.
### halter73/1145

```
$ ./multi-run.sh --depth 16
./run-wrk.sh -p 5000 -h 192.168.1.100 -t plaintext --script ../pipeline.lua -d 1m --depth 16 -c 512
Warming up...
4699696.24
Running tests...
4758701.48
4733957.38
4707075.01
4707825.09
4753937.18
4763750.12
4673806.49
4691102.53
4703620.58
4753383.33
4758701.48 4733957.38 4707075.01 4707825.09 4753937.18 4763750.12 4673806.49 4691102.53 4703620.58 4753383.33
```
### halter73/1145 + halter73/dont-write-at-the-same-time

```
$ ./multi-run.sh --depth 16
./run-wrk.sh -p 5000 -h 192.168.1.100 -t plaintext --script ../pipeline.lua -d 1m --depth 16 -c 512
Warming up...
4706377.81
Running tests...
4812169.18
4818584.28
4848651.40
4780047.91
4721708.67
4759027.05
4829114.36
4827255.34
4830057.89
4798915.02
4812169.18 4818584.28 4848651.40 4780047.91 4721708.67 4759027.05 4829114.36 4827255.34 4830057.89 4798915.02
```

@nathana1 @davidfowl @cesarbs

### CODE REVIEW

**Comment by nathana1** [comment]
Looks like you were using the default threadCount, the optimal threadCount for plaintext on this machine is 8.  When I reran with threadCount=8 I got about 4.9M, so about the new baseline.  Is the benchmark repo on that machine with or without your changes?

**Comment by halter73** [comment]
@nathana1 The benchmarks repo on the test server has a project reference to Kestrel. You can double check via git, but I think the halter73/1145 Kestrel branch is currently checked out with no further changes. I saw that halter73/1145 hat noticeably better RPS than dev.

**Comment by nathana1** [comment]
Yep, it's halter73/1145.

**Comment by benaadams** [comment]
@nathana1 are you seeing and difference going against coreclr 1.1.0 vs 1.0.1?

**Comment by nathana1** [comment]
It looks like coreclr 1.1.0 is about 1.5%-2% faster.

**Comment by halter73** [comment]
The perf improvement probably isn't dramatic enough for the lower safety (i.e. the possibility of really weird behavior given parallel writes).

**Pull request closed without merging**
