### PR TITLE
[Blocked] Use faster Unsafe.Read/CopyBlock methods

### PR DESCRIPTION
**Pull request by benaadams**
Needs `System.Runtime.CompilerServices.Unsafe` added to feed

Supersedes #804

Blocked on https://github.com/aspnet/Home/issues/1428

### CODE REVIEW

**Comment by geoffkizer** [comment]
Per @nathana1 #795, this doesn't seem to be a win.

I tried something similar with Buffer.MemoryCopy (unsafe version of BufferCopy.BlockCopy) and didn't see a win either -- actually seemed to make things slightly worse.

This is unfortunate.  I wish we could do better than BlockCopy, but not sure how to at this point...

**Comment by benaadams** [comment]
`Unsafe.Read<Vector<byte>>(block.DataFixedPtr + index);` is faster than `new Vector<byte>(array, index)`

Did assume rather than check `Unsafe.CopyBlock` :(

**Comment by benaadams** [comment]
`Unsafe.Read<Vector<byte>>(block.DataFixedPtr + index).CopyTo(array)` may therefore be better https://github.com/IllyriadGames/ByteArrayExtensions

However `BlockCopy` has been improved since then

**Comment by geoffkizer** [comment]
Definitely worth a look...

**Comment by benaadams** [comment]
Closing for now

**Pull request closed without merging**
