### PR TITLE
Go faster stripes

### PR DESCRIPTION
**Pull request by benaadams**
Has a bug and code is messy but @ 80% cpu

~/wrk$ wrk -c 1024 -d 30 -t 32 ...url.. -s ./scripts/pipeline.lua -- 16
Running 30s test @ http://url
  32 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    20.30ms   27.86ms 508.17ms   95.38%
    Req/Sec    30.19k     6.65k   53.32k    77.83%
  27798979 requests in 30.10s, 3.42GB read
  Socket errors: connect 35, read 0, write 0, timeout 0
Requests/sec: **923596.22**
Transfer/sec:    116.27MB

**Has a bug** that occasionally happens (neeeed sleep)

>    Microsoft.AspNet.Server.Kestrel.FunctionalTests.ResponseTests.LargeDownload [FAIL]
     System.Net.Http.HttpRequestException : An error occurred while sending the request.
     ---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response

### CODE REVIEW

**Comment by benaadams** [comment]
Now

~/wrk$ wrk -c 1024 -d 30 -t 32 http://url -s ./scripts/pipeline.lua -- 16
Running 30s test @ http://url
  32 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    16.15ms   15.10ms 278.97ms   81.29%
    Req/Sec    31.72k     5.98k   66.75k    72.80%
  29491574 requests in 30.10s, 3.63GB read
  Socket errors: connect 35, read 0, write 0, timeout 0
Requests/sec: **979796.86**
Transfer/sec:    123.34MB

**Comment by benaadams** [comment]
Using this benchmark change https://github.com/aspnet/benchmarks/pull/23

**Comment by benaadams** [comment]
Needs 2 runs to warm up; watching network, probably needs some more memory clean up

~/wrk$ wrk -c 1024 -d 30 -t 32 http://url -s ./scripts/pipeline.lua -- 16
Running 30s test @ http://url
  32 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    17.14ms   23.11ms 312.42ms   90.21%
    Req/Sec    31.32k     8.61k   87.35k    80.25%
  29846046 requests in 30.10s, 3.67GB read
  Socket errors: connect 35, read 0, write 0, timeout 0
Requests/sec: **991579.43**
Transfer/sec:    124.83MB

**Comment by AspNetSmurfLab** [comment]
@benaadams what were the results on your rig before this change? I've tried it here and it seems to substantially change the CPU profile, such that I now need to use many more connections (1024) than before in order to get high numbers. I'm now maxing CPU and hitting 505k RPS, which is about 7% more than before, although before we weren't quite maxing CPU.

**Comment by benaadams** [comment]
@AspNetSmurfLab very weird will look into it a bit more; before on 16 core 2GHz VM (Azure G4)

`wrk -c 256 -d 30 -t 32 ... -s ./scripts/pipeline.lua -- 16` 616K RPS 75% CPU
`wrk -c 1024 -d 30 -t 32 ... -s ./scripts/pipeline.lua -- 16` 587K RPS 73% CPU

So decreasing scaling; after (with the async local removal tweak in benchmarking)

`wrk -c 256 -d 30 -t 32 ... -s ./scripts/pipeline.lua -- 16` 523K RPS 60% CPU
`wrk -c 1024 -d 30 -t 32 ... -s ./scripts/pipeline.lua -- 16` 941K RPS 91% CPU

The decrease at 256 seems to be latency; so the before latency is 4.64ms and after it is 14.6ms; also this version needs a couple `wrk` runs to warm up; possibly to populate the `MemoryPool2`.

Will dig a little deeper, do a clean build etc and see if I can improve the latency.

**Comment by benaadams** [comment]
Also which arch? Am testing coreclr x64

**Comment by benaadams** [comment]
Closing for now as working on some code that will be ugly and don't want it as an open PR

**Pull request closed without merging**
