### PR TITLE
[WIP] Allocate Connection members on first read

### PR DESCRIPTION
**Pull request by cesarbs**
A little experiment I ran.

Right now we allocate a bunch of resources at the time a new connection is established: `SocketInput`, `SocketOuput`, `Frame`, etc. If that connection is never used, that's a bunch of wasted resources. This change waits until the first read to allocate those resources.

Some browsers (e.g. Chrome) might open more connections than they will actually use. For example, when I hit the sample app with Chrome, I see 4 connections, only 2 of which are actually used. If we extrapolate that to thousands of clients, memory usage on the server would be much higher than actually needed.

I tested this with 10,000 idle connections (after warming up with 10,000 active connections to get some slabs allocated). There's a ~17% reduction in memory usage. Results below.

## dev:

image

image

## This change:

image

image

No impact to plaintext benchmark.

**Edit**: updated with 10,000 idle connections opened after warming up the server with 10,000 active connections. Thanks @benaadams for pointing this out.

### CODE REVIEW

**Comment by davidfowl** [comment]
The call to StopAsync can happen from a non libuv thread so you need to make sure that things still work if StopAsync happens before the frame starts and after.

**Comment by benaadams** [comment]
Why is the `byte[]` so different between the two?

**Comment by cesarbs** [comment]
@benaadams Memory pool slabs. Good call, this is why the difference is so dramatic. Need to check difference with slabs already allocated.

**Comment by cesarbs** [comment]
A better test: open 10,000 connections, make a request on each, leave them all open. Close all. Force GC. Open 10,000 idle connections. Measure.

## dev:

image

image

## This change:

image

image

**Comment by halter73** [comment]
This was fixed in the more general case by https://github.com/aspnet/KestrelHttpServer/issues/699

**Pull request closed without merging**
