### PR TITLE
Use ArrayPool.Shared for small short lived byte[]

### PR DESCRIPTION
**Pull request by benaadams**
From  #519

Use ArrayPool<byte>.Shared for small short lived byte[]

### CODE REVIEW

**Comment by davidfowl** [comment]
Weird to mix the 2 pools no?

**Comment by benaadams** [comment]
Is only for short lived, short byte buffers; first is for the chunk length hex; and second is when the header value crosses two blocks - rather than getting a 4032 byte buffer from the pinned buffer pool for something that's only going be 10 bytes or the length of a header key.

**Comment by benaadams** [comment]
Updated description

**Comment by halter73** [comment]
I want to see if this makes any measurable impact with an applications that writes a bunch of small chunks.

**Comment by halter73** [comment]
I tested this using our LargeResponseApp sample project. I changed both `_chunkSize` and `_defaultNumChunks` to 256 and didn't set a content length.

I think these were pretty ideal circumstances to show the potential benefits of this change, but it seems to reduce the perf by nearly a factor of two. I'm not sure why. Maybe more cache misses?

I'm closing this until I see numbers that show a nice improvement.

Dev:

	Running 10s test @ http://10.0.0.100:5001/
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency   204.12ms  190.18ms   1.31s    86.67%
	    Req/Sec   520.06    105.98     1.15k    72.27%
	  162796 requests in 10.10s, 10.24GB read
	  Socket errors: connect 0, read 0, write 300, timeout 0
	Requests/sec:  16118.09
	Transfer/sec:      1.01GB

	Running 10s test @ http://10.0.0.100:5001/
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency   202.37ms  184.20ms   1.33s    85.29%
	    Req/Sec   513.45    115.76     2.26k    81.09%
	  161801 requests in 10.10s, 10.18GB read
	  Socket errors: connect 0, read 0, write 599, timeout 0
	Requests/sec:  16019.54
	Transfer/sec:      1.01GB

	Running 10s test @ http://10.0.0.100:5001/
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency   197.81ms  191.83ms   1.42s    87.11%
	    Req/Sec   522.46    107.31     1.67k    73.88%
	  163638 requests in 10.10s, 10.29GB read
	  Socket errors: connect 0, read 0, write 300, timeout 0
	Requests/sec:  16199.96
	Transfer/sec:      1.02GB

Merged (benaadams/buffer-pool-merged):

	Running 10s test @ http://10.0.0.100:5001/
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency   439.91ms  387.38ms   1.99s    78.35%
	    Req/Sec   282.25    126.37     1.03k    68.60%
	  90055 requests in 10.10s, 5.67GB read
	  Socket errors: connect 0, read 0, write 0, timeout 44
	Requests/sec:   8916.26
	Transfer/sec:    574.53MB

	Running 10s test @ http://10.0.0.100:5001/
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency   437.91ms  389.35ms   1.98s    78.64%
	    Req/Sec   284.54    128.41     0.87k    68.42%
	  90331 requests in 10.10s, 5.68GB read
	  Socket errors: connect 0, read 0, write 286, timeout 54
	Requests/sec:   8944.08
	Transfer/sec:    576.31MB

	Running 10s test @ http://10.0.0.100:5001/
	  32 threads and 256 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
	    Latency   438.57ms  387.66ms   2.00s    78.63%
	    Req/Sec   276.74    131.00     0.96k    69.47%
	  88286 requests in 10.10s, 5.55GB read
	  Socket errors: connect 0, read 0, write 525, timeout 64
	Requests/sec:   8741.10
	Transfer/sec:    563.16MB

**Comment by benaadams** [comment]
That's dreadful :(

**Pull request closed without merging**
