### PR TITLE
Add tests for HTTPS urls to AddressRegistrationTests (#794)

### PR DESCRIPTION
**Pull request by mikeharder**

### CODE REVIEW

**Comment by halter73** [comment]
So the plan is to test this with `Socket/SslStream` instead of `HttpClient` so it can pass on all OS X machines?

**Comment by mikeharder** [comment]
@halter73: Correct, I'm writing an HttpClientSlim which uses Socket+SslStream.

**Comment by Tratcher** [comment]
https://github.com/Tratcher/HttpClient/blob/dev/src/Microsoft.Net.Http.Client/ManagedHandler.cs

**Comment by mikeharder** [comment]
@halter73, @cesarbs, @Tratcher: Travis is now passing, ready for review.

**Comment by halter73** [comment]
:shipit:

**Comment by muratg** [comment]
Nice! 

:shipit:

**Pull request merged**
