### PR TITLE
Re-enable api check

### PR DESCRIPTION
**Pull request by JunTaoLuo**
#2350 Unblocked by https://github.com/aspnet/BuildTools/commit/d944172721e77b6ca05a512303a0859634786746

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
API check ran but it found a breaking change: https://github.com/aspnet/KestrelHttpServer/commit/fdb4184dbfdbac6ee8b53a4d8d1fbfaa8f60c0c1#diff-dfd6e5bf3bc39e44af0761394afeb8ecR16 and https://github.com/aspnet/KestrelHttpServer/commit/c3ba875d12cd43eeee1a2ab3a3a4ee3adac197a8#diff-dfd6e5bf3bc39e44af0761394afeb8ecR18. Should I add an exception or do we need to add an overload for the constructor?
cc @halter73

**Comment by davidfowl** [comment]
That package was never released to nuget.org so it's fine.

**Comment by JunTaoLuo** [comment]
@davidfowl in that case I think we should remove the baseline.json file.

**Comment by davidfowl** [comment]
> @davidfowl in that case I think we should remove the baseline.json file right?

Yep!

**Comment by JunTaoLuo** [comment]
@dotnet-bot test this please

**Comment by JunTaoLuo** [comment]
@dotnet-bot test Windows Release x64 Build

**Comment by JunTaoLuo** [comment]
API breaking change in https://github.com/aspnet/KestrelHttpServer/commit/abdcb47b8f96d7bf6554575e2d3493a7e955fc68

**Comment by davidfowl** [comment]
@JunTaoLuo I think you should skip libuv for API check and file a blocking bug in preivew2, then we need to discuss how we treat pubternal API changes that are in public APIs (specifically this public API).

/cc @DamianEdwards @Eilon

**Comment by Eilon** [comment]
@davidfowl it isn't clear to me what the breaking change is here by looking at the linked diffs. Changes in public APIs that use pubternals are not considered breaking changes by us, so those would be OK.

**Comment by JunTaoLuo** [comment]
@Eilon Actually it's not a pubternal breaking change. The method signature of the constructor of LibuvTransportFactory changed and it's a public type. I believe the discussion is that this type should have remained pubternal.

**Comment by JunTaoLuo** [comment]
Filed follow up issue at: https://github.com/aspnet/KestrelHttpServer/issues/2424. I want to unblock the API checks for the other packages ASAP.

**Comment by halter73** [comment]
IMHO The issue is that LibuvTransportFactory never should have been public. The only public way to use or configure libuv should be through the UseLibuv extension methods on IWebHostBuilder.

**Comment by JunTaoLuo** [comment]
@dotnet-bot test Ubuntu 16.04 Release Build

**Comment by halter73** [comment]
@ryanbrandenburg Are you saying that `src/Kestrel.Transport.Sockets/baseline.netcore.json` should be regenerated from the release/2.1 branch since it hasn't been shipped yet? If so, do we just regenerate the baseline if we change public API prior to 2.1 RTM?

**Comment by ryanbrandenburg** [comment]
@halter73 no, I'm saying that if we haven't shipped Kestrel.Transport.Sockets yet we should have a _blank_ file at `src/Kestrel.Transport.Sockets/baseline.netcore.json`. It indicates to future travelers "this space intentionally left blank", rather than that we just forgot to generate it.

**Comment by halter73** [comment]
@ryanbrandenburg @pranavkm Will either of you be mad if I cherry-pick b90766d09755c663e2af868380006213af1171f4 into Kestrel's release/2.1 branch?

**Comment by JunTaoLuo** [comment]
Absolutely furious, but I'll get over it. /s

**Comment by ryanbrandenburg** [comment]
@halter73 not as long as you then merge the resulting commit back into dev.

**Pull request merged**
