### PR TITLE
[2.1.1] Fix Json perf regression in Socket Transport

### PR DESCRIPTION
**Pull request by halter73**
#2573 

This PR is based on dev for now. Should we start preparing a patch branch?

### CODE REVIEW

**Comment by davidfowl** [comment]
Yes

**Comment by sebastienros** [comment]
Did you measure or should I?

**Comment by halter73** [comment]
@natemcmaster Should I create a release/2.1.1 branch based off of release/2.1 for this?

**Comment by sebastienros** [comment]
I built this branch locally and ran with and without this assembly in release on Linux. But it gets worse with this change at 261K vs 300K. We were almost at 320K before the regression.

**Comment by natemcmaster** [comment]
> Should I create a release/2.1.1 branch based off of release/2.1 for this?

You can use a branch named `halter73/release/2.1.1` if you want to stage multiple 2.1.1 fixes, but don't add a new `release/*` branch. Those have special meaning to our CI, and are also the way we keep track of changes that have patch approval. Once we finish RTM, 2.1.1 fixes will go into `release/2.1`.

**Comment by sebastienros** [comment]
I verified the performance numbers and the fix reverted the regression.

**Pull request merged**
