### PR TITLE
Fixing BadRequest tests to not try sending data after Bad Request

### PR DESCRIPTION
**Pull request by moozzyk**

### CODE REVIEW

**Comment by cesarbs** [comment]
:ship: when Travis goes green.

**Comment by halter73** [comment]
I think #917 is the more comprehensive/reliable fix.

**Comment by moozzyk** [comment]
Not sure if I like swallowing the exception - can it hide random failures?

**Comment by halter73** [comment]
This conversation might be better in #917, but I think my change is perfectly safe.

It's only catching an exception from a call to `Shutdown`. All tests that use `SendAllTryEnd` expect the server to respond with a 400 and reset the connection so it's not unexpected that the `Shutdown` will fail.

Initially I tried changing all the tests to just call `SendAll` instead of `SendEnd`. This would have been fine except for some of the `Theories` expect the request to be rejected because they're incomplete.

I could refactor the Theories and split up the test cases into ones that should call `SendAll` and those that should call `SendAllEnd`. Maybe this is better, but `Shutdown` failing isn't an issue, since we are always verifying we get the response that we expect.

**Comment by moozzyk** [comment]
We agreed that it would be good to have both fixes.

**Pull request merged**
