### PR TITLE
Spin off PlatformApis thing into separate library

### PR DESCRIPTION
**Pull request by thaiphan**
The whole cross-platform library loader helper stuff you guys have is pretty neat and I would like to use it for my own project. However, I'd rather not have a dependency on Kestrel so I just spun out the stuff I needed.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@thaiphan__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by thaiphan** [comment]
Has anybody had the opportunity to have a look at the pull request?

**Comment by davidfowl** [comment]
If we do this, it would be a runtime interface and service. It shouldn't be in this repository.

**Comment by thaiphan** [comment]
Uh, I was having trouble getting Edge.js working on Ubuntu and I'm pretty sure it's because of [this line](https://github.com/tjanczuk/edge/blob/840be77865b2d1756cb0ef2a222b820bc0f50c56/src/double/dotnet/EdgeJs.cs#L54). The idea was make a pull request to Edge.js to take advantage of this spun off library.

**Comment by thaiphan** [comment]
Has anybody had a look at my pull request yet?

**Comment by thaiphan** [comment]
Has anybody had a change to look at my pull request yet?

**Comment by thaiphan** [comment]
Hey again, is my pull request something you guys would be interested in accepting?

**Comment by thaiphan** [comment]
I don't imagine my pull request is particularly high priority but I'd at least appreciate some communication indicating such.

**Comment by davidfowl** [comment]
Sorry about that. We're not likely going to take this pull request. FWIW, it has come up a few times having an API that can be used that's just like this. We haven't decided to make this the API and when we do decide, it might live in a separate repository, or even end up being a CLR API.

For now I'd recommend copying the code.

**Pull request closed without merging**
