### PR TITLE
Faster Awaitable

### PR DESCRIPTION
**Pull request by Anderman**
See [Compare of actions is slow](https://github.com/aspnet/KestrelHttpServer/issues/555)

### CODE REVIEW

**Comment by halter73** [comment]
Wouldn't the simpler change be to change `!=` to `!object.ReferenceEquals`?

I'm a little concerned that moving the assignment of the continuation outside of the call to `CompareExchange` might introduce a subtle bug.

**Comment by Anderman** [comment]
Hmm, I don't think so but that looks even better without any risk.

**Comment by halter73** [comment]
Any reason not to just do this instead? https://github.com/aspnet/KestrelHttpServer/pull/558

**Comment by Anderman** [comment]
I still like the version with constants instead of ref to memory (slower)
and I was not completely convinced that this would lead to RC

But this not my daily business so I can be wrong.

The state is still checked / changed with the interlock statement.
The only thing that'is different is the `continuation action`. 

The producer reads only and the consumer does write and read.

So what could go wrong is that the producer reads an incorrect value if this value is set to late

```
var continuationPrev = _continuation;
            _continuation = continuation;

            var awaitableState = Interlocked.CompareExchange(
                ref _awaitableState,
                _awaitableIsContinue,
                _awaitableIsNotCompleted);
```
Maybe this can happen with out of order execution? Or if someone change the code.

**Comment by halter73** [comment]
I haven't looked at it closely enough to determine for sure whether not an RC is there, but I know it's definitely possible to introduce on with this type of change, and I don't want to risk it.

> ref to memory (slower)

Are you sure about that? It's not like we're actually following the reference to check equality if we take my PR.

**Comment by Anderman** [comment]
I understand. Should I close this one?

**Comment by halter73** [comment]
@Anderman I can close this.

Thanks for the PR and filing the issue.

**Pull request closed without merging**
