### PR TITLE
Simplify connection lifetime control flow [dev]

### PR DESCRIPTION
**Pull request by halter73**
Same as #1776 but for merging into dev.

### CODE REVIEW

**Comment by cesarbs** [comment]
Why not just merge back from `rel/2.0.0-preview1`?

**Comment by halter73** [comment]
@cesarbs That's exactly what I plan to do. I just wanted to see the tests passing since travis and appveyor don't run for PRs merged into non-dev branches.

**Comment by davidfowl** [comment]
AllowCertificateContinuesWhenNoCertificate failed

**Comment by halter73** [comment]
#1776 now targets the dev branch.

**Pull request closed without merging**
