### PR TITLE
fixed backlog setting

### PR DESCRIPTION
**Pull request by chopdown**

### CODE REVIEW

**Comment by Eilon** [comment]
@lodejard to look at the change.

@chopdown can you check out https://github.com/aspnet/Home/blob/master/CONTRIBUTING.md and fill out a contributor license agreement (CLA)? It's required for all PRs to the repos. Should only take a few minutes to go through.

**Comment by chopdown** [comment]
@Eilon CLA done.

**Comment by Eilon** [comment]
Thanks, waiting to see it show up on our side.

**Comment by Eilon** [comment]
CLA confirmed.

**Comment by Eilon** [comment]
@lodejard can you take a look?

**Pull request closed without merging**
