### PR TITLE
[Platform] Update to latest (add db routes)

### PR DESCRIPTION
**Pull request by benaadams**
/cc @sebastienros

### CODE REVIEW

**Comment by sebastienros** [comment]
@davidfowl what do you think with having db code in this repos? Or should we keep this part only in TE and just sync changes between the two repos, as we do with aspnet/Benchmarks.

**Comment by davidfowl** [comment]
I'm not a fan of putting this scenario here.

**Comment by benaadams** [comment]
Probably should live somewhere other than the TE repo? aspnet/Benchmarks then?

Could split it into more partial classes; separate the routing and db then have it as a src share for the non-db...

Will work something out; and see what you think.

**Comment by davidfowl** [comment]
Meh, it's fine to put it here. It's the lesser of all evils.

**Comment by muratg** [comment]
We’re closing this PR because we feel like Benchmarks is a better place to keep this. 

We thank you for the contribution and look forward to collaborating more in the future.

**Pull request closed without merging**
