### PR TITLE
Revert "Handle posting to the libuv thread after StopAsync (#2388)"

### PR DESCRIPTION
**Pull request by davidfowl**
This reverts commit 572627e88ce4db2ca2b3f18a200d5ff2a73fdead.

Turns out this regresses performance 😄 .  I'll have to catch on Abort....

/cc @benaadams

### CODE REVIEW

**Comment by halter73** [comment]
Who would have ever suspected? :rofl:

**Comment by davidfowl** [comment]
@halter73 will do.

**Comment by davidfowl** [comment]
@sebastienros hey I originally thought this was the regression but the variance on runs is killing me. I'm getting numbers that range from 1,493,133 to 1,590,242.

**Comment by sebastienros** [comment]
I assume you tried to keep the default warm-up and increase the duration?

**Comment by sebastienros** [comment]
Platform should be much higher on physical.

**Comment by davidfowl** [comment]
So we did change the default transport to Sockets and that seems to have made it all the way to the benchmarks server (we're at tip now) and maybe that's the problem? The strange thing is, I'd expect to see ~1.7 - 1.8 M RPS for plaintext but I'm seeing much less. 

So it seems like running without a transport means the driver hardcodes sockets? Maybe I'm running with the wrong transport. Stay tuned.

**Comment by sebastienros** [comment]
Windows machine?

**Comment by davidfowl** [comment]
Yep

**Comment by davidfowl** [comment]
@halter73 I'm going to do nothing with this PR for now because I cannot reproduce the regression that I thought I was seeing. Here are the numbers of the last 3 days of libuv plaintext:

```
3/15/18 4:41	KestrelLibuv http Plaintext	1860284	2.1.0-preview2-30335
3/14/18 22:45	KestrelLibuv http Plaintext	1875104	2.1.0-preview2-30330
3/14/18 19:42	KestrelLibuv http Plaintext	1820876	2.1.0-preview2-30327
3/14/18 16:40	KestrelLibuv http Plaintext	1812117	2.1.0-preview2-30324
3/14/18 13:40	KestrelLibuv http Plaintext	1845443	2.1.0-preview2-30324
3/14/18 10:40	KestrelLibuv http Plaintext	1858661	2.1.0-preview2-30323
3/14/18 7:39	KestrelLibuv http Plaintext	1882782	2.1.0-preview2-30322
3/14/18 6:09	KestrelLibuv http Plaintext	1829429	2.1.0-preview2-30322
3/14/18 4:38	KestrelLibuv http Plaintext	1857436	2.1.0-preview2-30320
3/14/18 2:16	KestrelLibuv http Plaintext	1834354	2.1.0-preview2-30311
3/14/18 1:05	KestrelLibuv http Plaintext	1853671	2.1.0-preview2-30311
3/13/18 19:42	KestrelLibuv http Plaintext	1846067	2.1.0-preview2-30301
3/13/18 16:38	KestrelLibuv http Plaintext	1859173	2.1.0-preview2-30301
3/13/18 13:40	KestrelLibuv http Plaintext	1833491	2.1.0-preview2-30301
3/13/18 10:42	KestrelLibuv http Plaintext	1813624	2.1.0-preview2-30301
3/13/18 8:11	KestrelLibuv http Plaintext	1811335	2.1.0-preview2-30301
3/13/18 7:05	KestrelLibuv http Plaintext	1785840	2.1.0-preview2-30301
```

**Comment by benaadams** [comment]
This is the asm for one of the current methods
```asm
Successfully inlined Monitor:Enter(ref,byref) (17 IL bytes) (depth 1) [profitable inline]
Successfully inlined UvAsyncHandle:Send():this (13 IL bytes) (depth 1) [below ALWAYS_INLINE size]
**************** Inline Tree
Inlines into 06000055 LibuvThread:Post(ref,ref):this
  [1 IL=0055 TR=000073 060024EA] [profitable inline] Monitor:Enter(ref,byref)
    [0 IL=0004 TR=000122 060024EB] [FAILED: does not return] Monitor:ThrowLockTakenException()
    [0 IL=0011 TR=000117 060024EC] [FAILED: noinline per IL/cached result] Monitor:ReliableEnter(ref,byref)
  [0 IL=0067 TR=000080 060000E7] [FAILED: noinline per IL/cached result] Queue`1:Enqueue(struct):this
  [0 IL=0078 TR=000103 060024ED] [FAILED: noinline per IL/cached result] Monitor:Exit(ref)
  [2 IL=0090 TR=000088 060000EB] [below ALWAYS_INLINE size] UvAsyncHandle:Send():this
    [0 IL=0007 TR=000129 060000BF] [FAILED: noinline per IL/cached result] LibuvFunctions:async_send(ref):this
Budget: initialTime=348, finalTime=380, initialBudget=3480, currentBudget=3480
Budget: initialSize=2320, finalSize=2468
; Assembly listing for method LibuvThread:Post(ref,ref):this
; Emitting BLENDED_CODE for X64 CPU with AVX
; optimized code
; rbp based frame
; fully interruptible
; Final local variable assignments
;
;  V00 this         [V00,T01] (  7,  7   )     ref  ->  rsi         this class-hnd
;  V01 TypeCtx      [V01,T05] (  4,  3.25)    long  ->  rdx        
;  V02 arg1         [V02,T06] (  3,  3   )     ref  ->  rdi         class-hnd
;  V03 arg2         [V03,T07] (  3,  3   )     ref  ->  rbx         class-hnd
;  V04 loc0         [V04    ] (  3,  3   )  struct (32) [rbp-0x48]   do-not-enreg[XSB] must-init addr-exposed
;* V05 loc1         [V05    ] (  0,  0   )  struct (32) zero-ref    ld-addr-op
;  V06 loc2         [V06,T08] (  4,  2.50)     ref  ->  [rbp-0x78]   do-not-enreg[H] class-hnd
;  V07 loc3         [V07    ] (  5,  4   )    bool  ->  [rbp-0x50]   do-not-enreg[XF] must-init addr-exposed ld-addr-op
;  V08 loc4         [V08,T04] (  4,  6.50)    long  ->  rcx        
;  V09 tmp1         [V09,T02] (  4,  8   )     ref  ->  rdx         class-hnd
;  V10 tmp2         [V10,T09] (  2,  2   )     ref  ->  rdx         V05.CallbackAdapter(offs=0x00) P-INDEP
;  V11 tmp3         [V11,T10] (  2,  2   )     ref  ->  rdi         V05.Callback(offs=0x08) P-INDEP
;  V12 tmp4         [V12,T11] (  2,  2   )     ref  ->  rbx         V05.State(offs=0x10) P-INDEP
;  V13 tmp5         [V13,T12] (  2,  2   )     ref  ->  r14         V05.Completion(offs=0x18) P-INDEP
;  V14 tmp6         [V14,T00] (  5, 10   )   byref  ->  rcx         stack-byref
;  V15 tmp7         [V15    ] (  5, 10   )  struct (32) [rbp-0x70]   do-not-enreg[XSB] must-init addr-exposed
;  V16 tmp8         [V16,T03] (  4,  8   )     ref  ->  rcx        
;  V17 OutArgs      [V17    ] (  1,  1   )  lclBlk (32) [rsp+0x00]  
;  V18 PSPSym       [V18    ] (  1,  1   )    long  ->  [rbp-0x80]   do-not-enreg[X] addr-exposed
;
; Lcl frame size = 128

G_M7850_IG01:
       55                   push     rbp
       4156                 push     r14
       57                   push     rdi
       56                   push     rsi
       53                   push     rbx
       4881EC80000000       sub      rsp, 128
       C5F877               vzeroupper 
       488DAC24A0000000     lea      rbp, [rsp+A0H]
       488BF1               mov      rsi, rcx
       488D7D90             lea      rdi, [rbp-70H]
       B912000000           mov      ecx, 18
       33C0                 xor      rax, rax
       F3AB                 rep stosd 
       488BCE               mov      rcx, rsi
       48896580             mov      qword ptr [rbp-80H], rsp
       488955D8             mov      qword ptr [rbp-28H], rdx
       488BF1               mov      rsi, rcx
       498BF8               mov      rdi, r8
       498BD9               mov      rbx, r9

G_M7850_IG02:
       4533F6               xor      r14, r14
       488B4A10             mov      rcx, qword ptr [rdx+16]
       488B4908             mov      rcx, qword ptr [rcx+8]
       4885C9               test     rcx, rcx
       7515                 jne      SHORT G_M7850_IG03
       488BCA               mov      rcx, rdx
       48BA305D00B1F97F0000 mov      rdx, 0x7FF9B1005D30
       E80222A75F           call     CORINFO_HELP_RUNTIMEHANDLE_METHOD
       488BC8               mov      rcx, rax

G_M7850_IG03:
       E8FABA9A5F           call     CORINFO_HELP_GETGENERICS_GCSTATIC_BASE
       488B10               mov      rdx, gword ptr [rax]
       488D4DB8             lea      rcx, bword ptr [rbp-48H]
       488911               mov      gword ptr [rcx], rdx
       48897908             mov      gword ptr [rcx+8], rdi
       48895910             mov      gword ptr [rcx+16], rbx
       4C897118             mov      gword ptr [rcx+24], r14
       488B5658             mov      rdx, gword ptr [rsi+88]
       48895588             mov      gword ptr [rbp-78H], rdx
       33D2                 xor      edx, edx
       8955B0               mov      dword ptr [rbp-50H], edx

G_M7850_IG04:
       807DB000             cmp      byte  ptr [rbp-50H], 0
       750F                 jne      SHORT G_M7850_IG06

G_M7850_IG05:
       488D55B0             lea      rdx, bword ptr [rbp-50H]
       488B4D88             mov      rcx, gword ptr [rbp-78H]
       E864B79E5F           call     Monitor:ReliableEnter(ref,byref)
       EB05                 jmp      SHORT G_M7850_IG07

G_M7850_IG06:
       E85DE4A553           call     Monitor:ThrowLockTakenException()

G_M7850_IG07:
       488B4E38             mov      rcx, gword ptr [rsi+56]

G_M7850_IG08:
       C4E17A6F45B8         vmovdqu  xmm0, qword ptr [rbp-48H]
       C4E17A7F4590         vmovdqu  qword ptr [rbp-70H], xmm0
       C4E17A6F45C8         vmovdqu  xmm0, qword ptr [rbp-38H]
       C4E17A7F45A0         vmovdqu  qword ptr [rbp-60H], xmm0

G_M7850_IG09:
       488D5590             lea      rdx, bword ptr [rbp-70H]
       3909                 cmp      dword ptr [rcx], ecx
       E886C8FFFF           call     Queue`1:Enqueue(struct):this
       90                   nop      

G_M7850_IG10:
       807DB000             cmp      byte  ptr [rbp-50H], 0
       7409                 je       SHORT G_M7850_IG11
       488B4D88             mov      rcx, gword ptr [rbp-78H]
       E806BE9E5F           call     Monitor:Exit(ref)

G_M7850_IG11:
       488B5630             mov      rdx, gword ptr [rsi+48]
       488B4A18             mov      rcx, gword ptr [rdx+24]
       3909                 cmp      dword ptr [rcx], ecx
       E837C9FFFF           call     LibuvFunctions:async_send(ref):this
       90                   nop      

G_M7850_IG12:
       488D65E0             lea      rsp, [rbp-20H]
       5B                   pop      rbx
       5E                   pop      rsi
       5F                   pop      rdi
       415E                 pop      r14
       5D                   pop      rbp
       C3                   ret      

G_M7850_IG13:
       55                   push     rbp
       4156                 push     r14
       57                   push     rdi
       56                   push     rsi
       53                   push     rbx
       4883EC30             sub      rsp, 48
       C5F877               vzeroupper 
       488B6920             mov      rbp, qword ptr [rcx+32]
       48896C2420           mov      qword ptr [rsp+20H], rbp
       488DADA0000000       lea      rbp, [rbp+A0H]

G_M7850_IG14:
       807DB000             cmp      byte  ptr [rbp-50H], 0
       7409                 je       SHORT G_M7850_IG15
       488B4D88             mov      rcx, gword ptr [rbp-78H]
       E8BFBD9E5F           call     Monitor:Exit(ref)

G_M7850_IG15:
       90                   nop      

G_M7850_IG16:
       4883C430             add      rsp, 48
       5B                   pop      rbx
       5E                   pop      rsi
       5F                   pop      rdi
       415E                 pop      r14
       5D                   pop      rbp
       C3                   ret      

; Total bytes of code 301, prolog size 60 for method LibuvThread:Post(ref,ref):this
```

**Comment by davidfowl** [comment]
False alarm. There is no regression here.

**Comment by benaadams** [comment]
Ah; that was pre, this is the post post
```asm
Successfully inlined SafeHandle:get_IsClosed():bool:this (12 IL bytes) (depth 1) [below ALWAYS_INLINE size]
Successfully inlined Monitor:Enter(ref,byref) (17 IL bytes) (depth 1) [profitable inline]
Successfully inlined UvAsyncHandle:Send():this (13 IL bytes) (depth 1) [below ALWAYS_INLINE size]
**************** Inline Tree
Inlines into 06000055 LibuvThread:Post(ref,ref):this
  [1 IL=0006 TR=000003 06004B3D] [below ALWAYS_INLINE size] SafeHandle:get_IsClosed():bool:this
  [2 IL=0069 TR=000083 060024EA] [profitable inline] Monitor:Enter(ref,byref)
    [0 IL=0004 TR=000155 060024EB] [FAILED: does not return] Monitor:ThrowLockTakenException()
    [0 IL=0011 TR=000150 060024EC] [FAILED: noinline per IL/cached result] Monitor:ReliableEnter(ref,byref)
  [0 IL=0081 TR=000090 060000E7] [FAILED: noinline per IL/cached result] Queue`1:Enqueue(struct):this
  [0 IL=0092 TR=000122 060024ED] [FAILED: noinline per IL/cached result] Monitor:Exit(ref)
  [3 IL=0105 TR=000101 060000EB] [below ALWAYS_INLINE size] UvAsyncHandle:Send():this
    [0 IL=0007 TR=000162 060000BF] [FAILED: noinline per IL/cached result] LibuvFunctions:async_send(ref):this
Budget: initialTime=408, finalTime=450, initialBudget=4080, currentBudget=4080
Budget: initialSize=2776, finalSize=2924
; Assembly listing for method LibuvThread:Post(ref,ref):this
; Emitting BLENDED_CODE for X64 CPU with AVX
; optimized code
; rbp based frame
; fully interruptible
; Final local variable assignments
;
;  V00 this         [V00,T00] (  9,  9   )     ref  ->  rsi         this class-hnd
;  V01 TypeCtx      [V01,T05] (  4,  3.50)    long  ->  rdx        
;  V02 arg1         [V02,T06] (  3,  3   )     ref  ->  rdi         class-hnd
;  V03 arg2         [V03,T07] (  3,  3   )     ref  ->  rbx         class-hnd
;  V04 loc0         [V04    ] (  3,  3   )  struct (32) [rbp-0x48]   do-not-enreg[XSB] must-init addr-exposed
;* V05 loc1         [V05    ] (  0,  0   )  struct (32) zero-ref    ld-addr-op
;  V06 loc2         [V06,T08] (  5,  4   )     ref  ->  [rbp-0x78]   do-not-enreg[H] class-hnd
;  V07 loc3         [V07    ] (  5,  4   )    bool  ->  [rbp-0x50]   do-not-enreg[XF] must-init addr-exposed ld-addr-op
;  V08 loc4         [V08,T04] (  4,  7   )    long  ->  rcx        
;* V09 tmp1         [V09    ] (  0,  0   )     ref  ->  zero-ref    class-hnd
;  V10 tmp2         [V10,T09] (  2,  4   )     ref  ->  rcx         class-hnd
;  V11 tmp3         [V11,T02] (  4,  8   )     ref  ->  rdx         class-hnd
;  V12 tmp4         [V12,T10] (  2,  2   )     ref  ->  rdx         V05.CallbackAdapter(offs=0x00) P-INDEP
;  V13 tmp5         [V13,T11] (  2,  2   )     ref  ->  rdi         V05.Callback(offs=0x08) P-INDEP
;  V14 tmp6         [V14,T12] (  2,  2   )     ref  ->  rbx         V05.State(offs=0x10) P-INDEP
;  V15 tmp7         [V15,T13] (  2,  2   )     ref  ->  r14         V05.Completion(offs=0x18) P-INDEP
;  V16 tmp8         [V16,T01] (  5, 10   )   byref  ->  rcx         stack-byref
;  V17 tmp9         [V17    ] (  5, 10   )  struct (32) [rbp-0x70]   do-not-enreg[XSB] must-init addr-exposed
;  V18 tmp10        [V18,T03] (  4,  8   )     ref  ->  rcx        
;  V19 OutArgs      [V19    ] (  1,  1   )  lclBlk (32) [rsp+0x00]  
;  V20 PSPSym       [V20    ] (  1,  1   )    long  ->  [rbp-0x80]   do-not-enreg[X] addr-exposed
;
; Lcl frame size = 128

G_M7851_IG01:
       55                   push     rbp
       4156                 push     r14
       57                   push     rdi
       56                   push     rsi
       53                   push     rbx
       4881EC80000000       sub      rsp, 128
       C5F877               vzeroupper 
       488DAC24A0000000     lea      rbp, [rsp+A0H]
       488BF1               mov      rsi, rcx
       488D7D90             lea      rdi, [rbp-70H]
       B912000000           mov      ecx, 18
       33C0                 xor      rax, rax
       F3AB                 rep stosd 
       488BCE               mov      rcx, rsi
       48896580             mov      qword ptr [rbp-80H], rsp
       488955D8             mov      qword ptr [rbp-28H], rdx
       488BF1               mov      rsi, rcx
       498BF8               mov      rdi, r8
       498BD9               mov      rbx, r9

G_M7851_IG02:
       488B4E30             mov      rcx, gword ptr [rsi+48]
       F6411001             test     byte  ptr [rcx+16], 1
       740B                 je       SHORT G_M7851_IG04

G_M7851_IG03:
       488D65E0             lea      rsp, [rbp-20H]
       5B                   pop      rbx
       5E                   pop      rsi
       5F                   pop      rdi
       415E                 pop      r14
       5D                   pop      rbp
       C3                   ret      

G_M7851_IG04:
       4533F6               xor      r14, r14
       488B4A10             mov      rcx, qword ptr [rdx+16]
       488B4908             mov      rcx, qword ptr [rcx+8]
       4885C9               test     rcx, rcx
       7515                 jne      SHORT G_M7851_IG05
       488BCA               mov      rcx, rdx
       48BA407EA3A8F97F0000 mov      rdx, 0x7FF9A8A37E40
       E81D21A85F           call     CORINFO_HELP_RUNTIMEHANDLE_METHOD
       488BC8               mov      rcx, rax

G_M7851_IG05:
       E815BA9B5F           call     CORINFO_HELP_GETGENERICS_GCSTATIC_BASE
       488B10               mov      rdx, gword ptr [rax]
       488D4DB8             lea      rcx, bword ptr [rbp-48H]
       488911               mov      gword ptr [rcx], rdx
       48897908             mov      gword ptr [rcx+8], rdi
       48895910             mov      gword ptr [rcx+16], rbx
       4C897118             mov      gword ptr [rcx+24], r14
       488B5658             mov      rdx, gword ptr [rsi+88]
       48895588             mov      gword ptr [rbp-78H], rdx
       33D2                 xor      edx, edx
       8955B0               mov      dword ptr [rbp-50H], edx

G_M7851_IG06:
       807DB000             cmp      byte  ptr [rbp-50H], 0
       750F                 jne      SHORT G_M7851_IG08

G_M7851_IG07:
       488D55B0             lea      rdx, bword ptr [rbp-50H]
       488B4D88             mov      rcx, gword ptr [rbp-78H]
       E87FB69F5F           call     Monitor:ReliableEnter(ref,byref)
       EB05                 jmp      SHORT G_M7851_IG09

G_M7851_IG08:
       E878E3C74F           call     Monitor:ThrowLockTakenException()

G_M7851_IG09:
       488B4E38             mov      rcx, gword ptr [rsi+56]

G_M7851_IG10:
       C4E17A6F45B8         vmovdqu  xmm0, qword ptr [rbp-48H]
       C4E17A7F4590         vmovdqu  qword ptr [rbp-70H], xmm0
       C4E17A6F45C8         vmovdqu  xmm0, qword ptr [rbp-38H]
       C4E17A7F45A0         vmovdqu  qword ptr [rbp-60H], xmm0

G_M7851_IG11:
       488D5590             lea      rdx, bword ptr [rbp-70H]
       3909                 cmp      dword ptr [rcx], ecx
       E871C8FFFF           call     Queue`1:Enqueue(struct):this
       90                   nop      

G_M7851_IG12:
       807DB000             cmp      byte  ptr [rbp-50H], 0
       740A                 je       SHORT G_M7851_IG13
       488B4D88             mov      rcx, gword ptr [rbp-78H]
       E821BD9F5F           call     Monitor:Exit(ref)
       90                   nop      

G_M7851_IG13:
       488B5630             mov      rdx, gword ptr [rsi+48]
       488B4A18             mov      rcx, gword ptr [rdx+24]
       3909                 cmp      dword ptr [rcx], ecx
       E821C9FFFF           call     LibuvFunctions:async_send(ref):this
       90                   nop      

G_M7851_IG14:
       488D65E0             lea      rsp, [rbp-20H]
       5B                   pop      rbx
       5E                   pop      rsi
       5F                   pop      rdi
       415E                 pop      r14
       5D                   pop      rbp
       C3                   ret      

G_M7851_IG15:
       55                   push     rbp
       4156                 push     r14
       57                   push     rdi
       56                   push     rsi
       53                   push     rbx
       4883EC30             sub      rsp, 48
       C5F877               vzeroupper 
       488B6920             mov      rbp, qword ptr [rcx+32]
       48896C2420           mov      qword ptr [rsp+20H], rbp
       488DADA0000000       lea      rbp, [rbp+A0H]

G_M7851_IG16:
       807DB000             cmp      byte  ptr [rbp-50H], 0
       7409                 je       SHORT G_M7851_IG17
       488B4D88             mov      rcx, gword ptr [rbp-78H]
       E8D9BC9F5F           call     Monitor:Exit(ref)

G_M7851_IG17:
       90                   nop      

G_M7851_IG18:
       4883C430             add      rsp, 48
       5B                   pop      rbx
       5E                   pop      rsi
       5F                   pop      rdi
       415E                 pop      r14
       5D                   pop      rbp
       C3                   ret      

G_M7851_IG19:
       55                   push     rbp
       4156                 push     r14
       57                   push     rdi
       56                   push     rsi
       53                   push     rbx
       4883EC30             sub      rsp, 48
       C5F877               vzeroupper 
       488B6920             mov      rbp, qword ptr [rcx+32]
       48896C2420           mov      qword ptr [rsp+20H], rbp
       488DADA0000000       lea      rbp, [rbp+A0H]

G_M7851_IG20:
       488D0599FFFFFF       lea      rax, G_M7851_IG14

G_M7851_IG21:
       4883C430             add      rsp, 48
       5B                   pop      rbx
       5E                   pop      rsi
       5F                   pop      rdi
       415E                 pop      r14
       5D                   pop      rbp
       C3                   ret      

; Total bytes of code 370, prolog size 60 for method LibuvThread:Post(ref,ref):this
```

**Comment by benaadams** [comment]
69 bytes more; but not crazily different

**Pull request closed without merging**
