### PR TITLE
[1.1.2] Check if request is aborted before verifying response bytes written (#1376)

### PR DESCRIPTION
**Pull request by cesarbs**
#1376

### CODE REVIEW

**Comment by natemcmaster** [comment]
Is this just a backport of another fix? I couldn't find the corresponding PR to dev

**Comment by cesarbs** [comment]
@natemcmaster dev PR: https://github.com/aspnet/KestrelHttpServer/pull/1499

**Comment by davidfowl** [comment]
Whats the deal with travis and appveyor

**Comment by Eilon** [comment]
This good to go in? CI seems happy. Do we have enough sign-offs?

**Pull request merged**
