### PR TITLE
Remove deprecated property KestrelServerOptions.MaxRequestBufferSize (#1027)

### PR DESCRIPTION
**Pull request by cesarbs**
#1027

### CODE REVIEW

**Comment by halter73** [comment]
You can just look at the existing exceptions.net45.json and exceptions.netcore.json and copy the pattern for removing `KestrelServerOptions.ConnectionFilter`. I made this change when the API check was still being run.

I think it will look like this:

```
  {
    "OldTypeId": "public class Microsoft.AspNetCore.Server.Kestrel.KestrelServerOptions",
    "OldMemberId": "public System.Nullable<System.Int64> get_MaxRequestBufferSize()",
    "Kind": "Removal"
  },
  {
    "OldTypeId": "public class Microsoft.AspNetCore.Server.Kestrel.KestrelServerOptions",
    "OldMemberId": "public System.Void set_MaxRequestBufferSize(System.Nullable<System.Int64> value)",
    "Kind": "Removal"
  },
```

If it's wrong we can fix it once the API check tool gets run.

**Comment by dougbu** [comment]
> how close are you to having API check ready for MSBuild?

Close but I've got another item to complete which is higher priority. I expect to get a PR for API Check next Monday or Tuesday.

Actually, the main thing blocking check-in is determining which repos or projects (when only one or two are broken in a repo) need API checks disabled initially. I'll probably run a Universe build over the weekend to get some idea of the current state. Worst case, could merge the feature but leave it off everywhere by default.

**Comment by halter73** [comment]
@cesarbs Are you going to merge this soon?

**Comment by cesarbs** [comment]
@halter73 I will once I figure out why ApiCheck gives me these error messages:

```
ERROR: The following exclusion is in the exclusion file, but is no longer necessary:
    Old type: public class Microsoft.AspNetCore.Server.Kestrel.KestrelServerOptions
    Old member: public System.Nullable<System.Int64> get_MaxRequestBufferSize()
    New type:
    New member:

ERROR: The following exclusion is in the exclusion file, but is no longer necessary:
    Old type: public class Microsoft.AspNetCore.Server.Kestrel.KestrelServerOptions
    Old member: public System.Void set_MaxRequestBufferSize(System.Nullable<System.Int64> value)
    New type:
    New member:
```

This is how I ran it:

```
dotnet run -f netcoreapp1.1 compare -b D:\src\aspnet\KestrelHttpServer\src\Microsoft.AspNetCo
re.Server.Kestrel\baseline.netcore.json -e D:\src\aspnet\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel\exceptions.netcore.json -a D:\src\aspnet\Kest
relHttpServer\src\Microsoft.AspNetCore.Server.Kestrel\bin\Debug\netstandard1.3\Microsoft.AspNetCore.Server.Kestrel.dll -p D:\src\aspnet\KestrelHttpServer\src\Mi
crosoft.AspNetCore.Server.Kestrel\obj\project.assets.json -f netstandard1.3 -epi
```

**Comment by cesarbs** [comment]
Updated. At this point, we don't care about API check anymore right?

**Comment by dougbu** [comment]
> At this point, we don't care about API check anymore right?

We care in general. However, I believe __the powers that be:tm:__ 👑 decided to disable the checks for this repo. Surprised a commit to do that hasn't already gone in -- if I'm correct.

**Comment by davidfowl** [comment]
@cesarbs merge it 😄

**Pull request merged**
