### PR TITLE
Added "308 Permanent Redirect" to ReasonPhrases

### PR DESCRIPTION
**Pull request by khellang**
From RFC7538 - https://tools.ietf.org/html/rfc7538

### CODE REVIEW

**Comment by khellang** [comment]
Also, are you interested in a PR for "451 Unavailable For Legal Reasons" ([RFC7725](https://tools.ietf.org/html/rfc7725))? I see it's missing from the HTTP abstractions as well...

**Comment by cesarbs** [comment]
:ship:

**Comment by cesarbs** [comment]
@muratg @Eilon @davidfowl What's your take on 451?

**Comment by halter73** [comment]
:shipit: 308 seems like a pretty safe. I would take 451 too because why not?

**Comment by khellang** [comment]
Submitted 451 as well... #930

**Comment by muratg** [comment]
Seems safe and nice to me too. Though bar for 1.0.0 is very high now, so we'll get this in once we branch for RTM.

**Comment by cesarbs** [comment]
Let's merge this. :ship:

**Pull request merged**
