### PR TITLE
Fix build issues

### PR DESCRIPTION
**Pull request by benaadams**
Fixes some loose ends that prevent the CI build

/cc @halter73 @cesarbs

### CODE REVIEW

**Comment by benaadams** [comment]
Alas still has the `Unhandled Exception: System.Diagnostics.Debug+DebugAssertException: Block being garbage collected instead of returned to pool` issue on travis

Rest of the stuff works though

**Comment by halter73** [comment]
That assertion was only recently enabled by https://github.com/aspnet/KestrelHttpServer/pull/623, and I haven't seen a Travis pass since that inclusion. I'll see if I can reproduce on my Ubuntu machine.

**Comment by benaadams** [comment]
I think its on shutdown; seems to be after all the tests pass

**Comment by cesarbs** [comment]
I'm seeing that assertion too. Trying to track down where it's coming from.

**Comment by halter73** [comment]
All the components of the issues have been merged. Next time we see `System.Diagnostics.Debug+DebugAssertException: Block being garbage collected instead of returned to pool`, I'm filing an issue.

**Comment by cesarbs** [comment]
@halter73 I've seen it and I'm investigating. I've finally managed to get a repro :grin:

**Pull request closed without merging**
