### PR TITLE
Faster output header handling

### PR DESCRIPTION
**Pull request by benaadams**
From  #519

### CODE REVIEW

**Comment by davidfowl** [comment]
How much does this actually save?

**Comment by benaadams** [comment]
It could save more, but are some oddities with nulls (being valid stored values but not output; is even a test for it and related things)

Otherwise a fair bit and moves `CreateResponseHeader` out of the heavy functions; as without it, it repeatedly does:

`new Enumerator -> Movenext -> Current -> Movenext` for every header; as well as keep-alive check

**Comment by davidfowl** [comment]
@benaadams I'd like to see numbers. This looks like an uber micro-optimization.

**Comment by benaadams** [comment]
Perf is in https://github.com/aspnet/KestrelHttpServer/pull/519#issuecomment-166891420

Numbers are hard to get matching; but look at the ratios for FrameResponseHeaders.CopyToFast - CopyFrom is the same in both

Pre change 
pre-change
Without
post-change

**Comment by benaadams** [comment]
Can run longer perf tests if you want more equivalent numbers?

**Comment by benaadams** [comment]
@davidfowl some might be related to: https://github.com/aspnet/Common/pull/74

**Comment by benaadams** [comment]
`StringValues` enumerator is currently fairly inefficient; this might become a de-opt after PR https://github.com/aspnet/Common/pull/74

**Comment by benaadams** [comment]
Merged with  #524 due to Generated file clash

**Pull request closed without merging**
